# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/sd_fat32_controller/sd_fat32_controller.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sd_fat32_controller || ORIG_REF_NAME==sd_fat32_controller}]

# IP: bd/sd_fat32_controller/ip/sd_fat32_controller_mig_7series_0_1/sd_fat32_controller_mig_7series_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sd_fat32_controller_mig_7series_0_1 || ORIG_REF_NAME==sd_fat32_controller_mig_7series_0_1}]

# IP: bd/sd_fat32_controller/ip/sd_fat32_controller_clk_wiz_0_0/sd_fat32_controller_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sd_fat32_controller_clk_wiz_0_0 || ORIG_REF_NAME==sd_fat32_controller_clk_wiz_0_0}]

# IP: bd/sd_fat32_controller/ip/sd_fat32_controller_axi_uartlite_0_0/sd_fat32_controller_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sd_fat32_controller_axi_uartlite_0_0 || ORIG_REF_NAME==sd_fat32_controller_axi_uartlite_0_0}]

# IP: bd/sd_fat32_controller/ip/sd_fat32_controller_microblaze_0_0/sd_fat32_controller_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sd_fat32_controller_microblaze_0_0 || ORIG_REF_NAME==sd_fat32_controller_microblaze_0_0}]

# IP: bd/sd_fat32_controller/ip/sd_fat32_controller_dlmb_v10_0/sd_fat32_controller_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sd_fat32_controller_dlmb_v10_0 || ORIG_REF_NAME==sd_fat32_controller_dlmb_v10_0}]

# IP: bd/sd_fat32_controller/ip/sd_fat32_controller_ilmb_v10_0/sd_fat32_controller_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sd_fat32_controller_ilmb_v10_0 || ORIG_REF_NAME==sd_fat32_controller_ilmb_v10_0}]

# IP: bd/sd_fat32_controller/ip/sd_fat32_controller_dlmb_bram_if_cntlr_0/sd_fat32_controller_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sd_fat32_controller_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==sd_fat32_controller_dlmb_bram_if_cntlr_0}]

# IP: bd/sd_fat32_controller/ip/sd_fat32_controller_ilmb_bram_if_cntlr_0/sd_fat32_controller_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sd_fat32_controller_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==sd_fat32_controller_ilmb_bram_if_cntlr_0}]

# IP: bd/sd_fat32_controller/ip/sd_fat32_controller_lmb_bram_0/sd_fat32_controller_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sd_fat32_controller_lmb_bram_0 || ORIG_REF_NAME==sd_fat32_controller_lmb_bram_0}]

# IP: bd/sd_fat32_controller/ip/sd_fat32_controller_microblaze_0_axi_periph_0/sd_fat32_controller_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sd_fat32_controller_microblaze_0_axi_periph_0 || ORIG_REF_NAME==sd_fat32_controller_microblaze_0_axi_periph_0}]

# IP: bd/sd_fat32_controller/ip/sd_fat32_controller_mdm_1_0/sd_fat32_controller_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sd_fat32_controller_mdm_1_0 || ORIG_REF_NAME==sd_fat32_controller_mdm_1_0}]

# IP: bd/sd_fat32_controller/ip/sd_fat32_controller_rst_clk_wiz_0_100M_0/sd_fat32_controller_rst_clk_wiz_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sd_fat32_controller_rst_clk_wiz_0_100M_0 || ORIG_REF_NAME==sd_fat32_controller_rst_clk_wiz_0_100M_0}]

# IP: bd/sd_fat32_controller/ip/sd_fat32_controller_axi_mem_intercon_0/sd_fat32_controller_axi_mem_intercon_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sd_fat32_controller_axi_mem_intercon_0 || ORIG_REF_NAME==sd_fat32_controller_axi_mem_intercon_0}]

# IP: bd/sd_fat32_controller/ip/sd_fat32_controller_xbar_0/sd_fat32_controller_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sd_fat32_controller_xbar_0 || ORIG_REF_NAME==sd_fat32_controller_xbar_0}]

# IP: bd/sd_fat32_controller/ip/sd_fat32_controller_rst_mig_7series_0_75M_0/sd_fat32_controller_rst_mig_7series_0_75M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sd_fat32_controller_rst_mig_7series_0_75M_0 || ORIG_REF_NAME==sd_fat32_controller_rst_mig_7series_0_75M_0}]

# IP: bd/sd_fat32_controller/ip/sd_fat32_controller_xbar_1/sd_fat32_controller_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sd_fat32_controller_xbar_1 || ORIG_REF_NAME==sd_fat32_controller_xbar_1}]

# IP: bd/sd_fat32_controller/ip/sd_fat32_controller_PmodSD_0_1/sd_fat32_controller_PmodSD_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sd_fat32_controller_PmodSD_0_1 || ORIG_REF_NAME==sd_fat32_controller_PmodSD_0_1}]

# IP: bd/sd_fat32_controller/ip/sd_fat32_controller_PmodSD_0_1/src/PmodSD_axi_gpio_0_0/PmodSD_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PmodSD_axi_gpio_0_0 || ORIG_REF_NAME==PmodSD_axi_gpio_0_0}]

# IP: bd/sd_fat32_controller/ip/sd_fat32_controller_PmodSD_0_1/src/PmodSD_axi_quad_spi_0_0/PmodSD_axi_quad_spi_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PmodSD_axi_quad_spi_0_0 || ORIG_REF_NAME==PmodSD_axi_quad_spi_0_0}]

# IP: bd/sd_fat32_controller/ip/sd_fat32_controller_PmodSD_0_1/src/PmodSD_pmod_bridge_0_0/PmodSD_pmod_bridge_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PmodSD_pmod_bridge_0_0 || ORIG_REF_NAME==PmodSD_pmod_bridge_0_0}]

# IP: bd/sd_fat32_controller/ip/sd_fat32_controller_auto_cc_0/sd_fat32_controller_auto_cc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sd_fat32_controller_auto_cc_0 || ORIG_REF_NAME==sd_fat32_controller_auto_cc_0}]

# IP: bd/sd_fat32_controller/ip/sd_fat32_controller_auto_us_0/sd_fat32_controller_auto_us_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sd_fat32_controller_auto_us_0 || ORIG_REF_NAME==sd_fat32_controller_auto_us_0}]

# IP: bd/sd_fat32_controller/ip/sd_fat32_controller_auto_us_1/sd_fat32_controller_auto_us_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sd_fat32_controller_auto_us_1 || ORIG_REF_NAME==sd_fat32_controller_auto_us_1}]

# XDC: bd/sd_fat32_controller/ip/sd_fat32_controller_mig_7series_0_1/sd_fat32_controller_mig_7series_0_1/user_design/constraints/sd_fat32_controller_mig_7series_0_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sd_fat32_controller_mig_7series_0_1 || ORIG_REF_NAME==sd_fat32_controller_mig_7series_0_1}]

# XDC: bd/sd_fat32_controller/ip/sd_fat32_controller_mig_7series_0_1/sd_fat32_controller_mig_7series_0_1/user_design/constraints/sd_fat32_controller_mig_7series_0_1_ooc.xdc

# XDC: bd/sd_fat32_controller/ip/sd_fat32_controller_mig_7series_0_1/sd_fat32_controller_mig_7series_0_1_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sd_fat32_controller_mig_7series_0_1 || ORIG_REF_NAME==sd_fat32_controller_mig_7series_0_1}]

# XDC: bd/sd_fat32_controller/ip/sd_fat32_controller_clk_wiz_0_0/sd_fat32_controller_clk_wiz_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==sd_fat32_controller_clk_wiz_0_0 || ORIG_REF_NAME==sd_fat32_controller_clk_wiz_0_0}] {/inst }]/inst ]]

# XDC: bd/sd_fat32_controller/ip/sd_fat32_controller_clk_wiz_0_0/sd_fat32_controller_clk_wiz_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==sd_fat32_controller_clk_wiz_0_0 || ORIG_REF_NAME==sd_fat32_controller_clk_wiz_0_0}] {/inst }]/inst ]]

# XDC: bd/sd_fat32_controller/ip/sd_fat32_controller_clk_wiz_0_0/sd_fat32_controller_clk_wiz_0_0_ooc.xdc

# XDC: bd/sd_fat32_controller/ip/sd_fat32_controller_axi_uartlite_0_0/sd_fat32_controller_axi_uartlite_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==sd_fat32_controller_axi_uartlite_0_0 || ORIG_REF_NAME==sd_fat32_controller_axi_uartlite_0_0}] {/U0 }]/U0 ]]

# XDC: bd/sd_fat32_controller/ip/sd_fat32_controller_axi_uartlite_0_0/sd_fat32_controller_axi_uartlite_0_0_ooc.xdc

# XDC: bd/sd_fat32_controller/ip/sd_fat32_controller_axi_uartlite_0_0/sd_fat32_controller_axi_uartlite_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==sd_fat32_controller_axi_uartlite_0_0 || ORIG_REF_NAME==sd_fat32_controller_axi_uartlite_0_0}] {/U0 }]/U0 ]]

# XDC: bd/sd_fat32_controller/ip/sd_fat32_controller_microblaze_0_0/sd_fat32_controller_microblaze_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==sd_fat32_controller_microblaze_0_0 || ORIG_REF_NAME==sd_fat32_controller_microblaze_0_0}] {/U0 }]/U0 ]]

# XDC: bd/sd_fat32_controller/ip/sd_fat32_controller_microblaze_0_0/sd_fat32_controller_microblaze_0_0_ooc_debug.xdc

# XDC: bd/sd_fat32_controller/ip/sd_fat32_controller_microblaze_0_0/sd_fat32_controller_microblaze_0_0_ooc.xdc

# XDC: bd/sd_fat32_controller/ip/sd_fat32_controller_dlmb_v10_0/sd_fat32_controller_dlmb_v10_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==sd_fat32_controller_dlmb_v10_0 || ORIG_REF_NAME==sd_fat32_controller_dlmb_v10_0}] {/U0 }]/U0 ]]

# XDC: bd/sd_fat32_controller/ip/sd_fat32_controller_dlmb_v10_0/sd_fat32_controller_dlmb_v10_0_ooc.xdc

# XDC: bd/sd_fat32_controller/ip/sd_fat32_controller_ilmb_v10_0/sd_fat32_controller_ilmb_v10_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==sd_fat32_controller_ilmb_v10_0 || ORIG_REF_NAME==sd_fat32_controller_ilmb_v10_0}] {/U0 }]/U0 ]]

# XDC: bd/sd_fat32_controller/ip/sd_fat32_controller_ilmb_v10_0/sd_fat32_controller_ilmb_v10_0_ooc.xdc

# XDC: bd/sd_fat32_controller/ip/sd_fat32_controller_dlmb_bram_if_cntlr_0/sd_fat32_controller_dlmb_bram_if_cntlr_0_ooc.xdc

# XDC: bd/sd_fat32_controller/ip/sd_fat32_controller_ilmb_bram_if_cntlr_0/sd_fat32_controller_ilmb_bram_if_cntlr_0_ooc.xdc

# XDC: bd/sd_fat32_controller/ip/sd_fat32_controller_lmb_bram_0/sd_fat32_controller_lmb_bram_0_ooc.xdc

# XDC: bd/sd_fat32_controller/ip/sd_fat32_controller_mdm_1_0/sd_fat32_controller_mdm_1_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==sd_fat32_controller_mdm_1_0 || ORIG_REF_NAME==sd_fat32_controller_mdm_1_0}] {/U0 }]/U0 ]]

# XDC: bd/sd_fat32_controller/ip/sd_fat32_controller_mdm_1_0/sd_fat32_controller_mdm_1_0_ooc_trace.xdc

# XDC: bd/sd_fat32_controller/ip/sd_fat32_controller_rst_clk_wiz_0_100M_0/sd_fat32_controller_rst_clk_wiz_0_100M_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sd_fat32_controller_rst_clk_wiz_0_100M_0 || ORIG_REF_NAME==sd_fat32_controller_rst_clk_wiz_0_100M_0}]

# XDC: bd/sd_fat32_controller/ip/sd_fat32_controller_rst_clk_wiz_0_100M_0/sd_fat32_controller_rst_clk_wiz_0_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sd_fat32_controller_rst_clk_wiz_0_100M_0 || ORIG_REF_NAME==sd_fat32_controller_rst_clk_wiz_0_100M_0}]

# XDC: bd/sd_fat32_controller/ip/sd_fat32_controller_rst_clk_wiz_0_100M_0/sd_fat32_controller_rst_clk_wiz_0_100M_0_ooc.xdc

# XDC: bd/sd_fat32_controller/ip/sd_fat32_controller_xbar_0/sd_fat32_controller_xbar_0_ooc.xdc

# XDC: bd/sd_fat32_controller/ip/sd_fat32_controller_rst_mig_7series_0_75M_0/sd_fat32_controller_rst_mig_7series_0_75M_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sd_fat32_controller_rst_mig_7series_0_75M_0 || ORIG_REF_NAME==sd_fat32_controller_rst_mig_7series_0_75M_0}]

# XDC: bd/sd_fat32_controller/ip/sd_fat32_controller_rst_mig_7series_0_75M_0/sd_fat32_controller_rst_mig_7series_0_75M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sd_fat32_controller_rst_mig_7series_0_75M_0 || ORIG_REF_NAME==sd_fat32_controller_rst_mig_7series_0_75M_0}]

# XDC: bd/sd_fat32_controller/ip/sd_fat32_controller_rst_mig_7series_0_75M_0/sd_fat32_controller_rst_mig_7series_0_75M_0_ooc.xdc

# XDC: bd/sd_fat32_controller/ip/sd_fat32_controller_xbar_1/sd_fat32_controller_xbar_1_ooc.xdc

# XDC: bd/sd_fat32_controller/ip/sd_fat32_controller_PmodSD_0_1/sd_fat32_controller_PmodSD_0_1_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==sd_fat32_controller_PmodSD_0_1 || ORIG_REF_NAME==sd_fat32_controller_PmodSD_0_1}] {/inst }]/inst ]]

# XDC: bd/sd_fat32_controller/ip/sd_fat32_controller_PmodSD_0_1/src/PmodSD_axi_gpio_0_0/PmodSD_axi_gpio_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodSD_axi_gpio_0_0 || ORIG_REF_NAME==PmodSD_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: bd/sd_fat32_controller/ip/sd_fat32_controller_PmodSD_0_1/src/PmodSD_axi_gpio_0_0/PmodSD_axi_gpio_0_0_ooc.xdc

# XDC: bd/sd_fat32_controller/ip/sd_fat32_controller_PmodSD_0_1/src/PmodSD_axi_gpio_0_0/PmodSD_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodSD_axi_gpio_0_0 || ORIG_REF_NAME==PmodSD_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: bd/sd_fat32_controller/ip/sd_fat32_controller_PmodSD_0_1/src/PmodSD_axi_quad_spi_0_0/PmodSD_axi_quad_spi_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodSD_axi_quad_spi_0_0 || ORIG_REF_NAME==PmodSD_axi_quad_spi_0_0}] {/U0 }]/U0 ]]

# XDC: bd/sd_fat32_controller/ip/sd_fat32_controller_PmodSD_0_1/src/PmodSD_axi_quad_spi_0_0/PmodSD_axi_quad_spi_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodSD_axi_quad_spi_0_0 || ORIG_REF_NAME==PmodSD_axi_quad_spi_0_0}] {/U0 }]/U0 ]]

# XDC: bd/sd_fat32_controller/ip/sd_fat32_controller_PmodSD_0_1/src/PmodSD_axi_quad_spi_0_0/PmodSD_axi_quad_spi_0_0_ooc.xdc

# XDC: bd/sd_fat32_controller/ip/sd_fat32_controller_PmodSD_0_1/src/PmodSD_axi_quad_spi_0_0/PmodSD_axi_quad_spi_0_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodSD_axi_quad_spi_0_0 || ORIG_REF_NAME==PmodSD_axi_quad_spi_0_0}] {/U0 }]/U0 ]]

# XDC: bd/sd_fat32_controller/ip/sd_fat32_controller_PmodSD_0_1/src/PmodSD_pmod_bridge_0_0/PmodSD_pmod_bridge_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodSD_pmod_bridge_0_0 || ORIG_REF_NAME==PmodSD_pmod_bridge_0_0}] {/inst }]/inst ]]

# XDC: bd/sd_fat32_controller/ip/sd_fat32_controller_PmodSD_0_1/src/PmodSD_pmod_bridge_0_0/src/pmod_concat_ooc.xdc

# XDC: bd/sd_fat32_controller/ip/sd_fat32_controller_PmodSD_0_1/src/PmodSD_ooc.xdc

# XDC: bd/sd_fat32_controller/ip/sd_fat32_controller_auto_cc_0/sd_fat32_controller_auto_cc_0_ooc.xdc

# XDC: bd/sd_fat32_controller/ip/sd_fat32_controller_auto_cc_0/sd_fat32_controller_auto_cc_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==sd_fat32_controller_auto_cc_0 || ORIG_REF_NAME==sd_fat32_controller_auto_cc_0}] {/inst }]/inst ]]

# XDC: bd/sd_fat32_controller/ip/sd_fat32_controller_auto_us_0/sd_fat32_controller_auto_us_0_ooc.xdc

# XDC: bd/sd_fat32_controller/ip/sd_fat32_controller_auto_us_0/sd_fat32_controller_auto_us_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==sd_fat32_controller_auto_us_0 || ORIG_REF_NAME==sd_fat32_controller_auto_us_0}] {/inst }]/inst ]]

# XDC: bd/sd_fat32_controller/ip/sd_fat32_controller_auto_us_1/sd_fat32_controller_auto_us_1_ooc.xdc

# XDC: bd/sd_fat32_controller/ip/sd_fat32_controller_auto_us_1/sd_fat32_controller_auto_us_1_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==sd_fat32_controller_auto_us_1 || ORIG_REF_NAME==sd_fat32_controller_auto_us_1}] {/inst }]/inst ]]

# XDC: bd/sd_fat32_controller/sd_fat32_controller_ooc.xdc
