# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/FPGA/Trash/sd_fat32_2.0/sd_fat32_2.0.cache/wt [current_project]
set_property parent.project_path D:/FPGA/Trash/sd_fat32_2.0/sd_fat32_2.0.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:nexys-a7-100t:part0:1.0 [current_project]
set_property ip_repo_paths c:/Xilinx/Vivado/2015.4/data/vivado-library [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
add_files D:/FPGA/Trash/sd_fat32_2.0/sd_fat32_2.0.srcs/sources_1/bd/sd_fat32_controller/sd_fat32_controller.bd
set_property used_in_implementation false [get_files -all d:/FPGA/Trash/sd_fat32_2.0/sd_fat32_2.0.srcs/sources_1/bd/sd_fat32_controller/ip/sd_fat32_controller_mig_7series_0_1/sd_fat32_controller_mig_7series_0_1/user_design/constraints/sd_fat32_controller_mig_7series_0_1.xdc]
set_property used_in_implementation false [get_files -all d:/FPGA/Trash/sd_fat32_2.0/sd_fat32_2.0.srcs/sources_1/bd/sd_fat32_controller/ip/sd_fat32_controller_mig_7series_0_1/sd_fat32_controller_mig_7series_0_1/user_design/constraints/sd_fat32_controller_mig_7series_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/FPGA/Trash/sd_fat32_2.0/sd_fat32_2.0.srcs/sources_1/bd/sd_fat32_controller/ip/sd_fat32_controller_mig_7series_0_1/sd_fat32_controller_mig_7series_0_1_board.xdc]
set_property used_in_implementation false [get_files -all d:/FPGA/Trash/sd_fat32_2.0/sd_fat32_2.0.srcs/sources_1/bd/sd_fat32_controller/ip/sd_fat32_controller_clk_wiz_0_0/sd_fat32_controller_clk_wiz_0_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/FPGA/Trash/sd_fat32_2.0/sd_fat32_2.0.srcs/sources_1/bd/sd_fat32_controller/ip/sd_fat32_controller_clk_wiz_0_0/sd_fat32_controller_clk_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/FPGA/Trash/sd_fat32_2.0/sd_fat32_2.0.srcs/sources_1/bd/sd_fat32_controller/ip/sd_fat32_controller_clk_wiz_0_0/sd_fat32_controller_clk_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/FPGA/Trash/sd_fat32_2.0/sd_fat32_2.0.srcs/sources_1/bd/sd_fat32_controller/ip/sd_fat32_controller_axi_uartlite_0_0/sd_fat32_controller_axi_uartlite_0_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/FPGA/Trash/sd_fat32_2.0/sd_fat32_2.0.srcs/sources_1/bd/sd_fat32_controller/ip/sd_fat32_controller_axi_uartlite_0_0/sd_fat32_controller_axi_uartlite_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/FPGA/Trash/sd_fat32_2.0/sd_fat32_2.0.srcs/sources_1/bd/sd_fat32_controller/ip/sd_fat32_controller_axi_uartlite_0_0/sd_fat32_controller_axi_uartlite_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/FPGA/Trash/sd_fat32_2.0/sd_fat32_2.0.srcs/sources_1/bd/sd_fat32_controller/ip/sd_fat32_controller_microblaze_0_0/sd_fat32_controller_microblaze_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/FPGA/Trash/sd_fat32_2.0/sd_fat32_2.0.srcs/sources_1/bd/sd_fat32_controller/ip/sd_fat32_controller_microblaze_0_0/sd_fat32_controller_microblaze_0_0_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all d:/FPGA/Trash/sd_fat32_2.0/sd_fat32_2.0.srcs/sources_1/bd/sd_fat32_controller/ip/sd_fat32_controller_microblaze_0_0/sd_fat32_controller_microblaze_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/FPGA/Trash/sd_fat32_2.0/sd_fat32_2.0.srcs/sources_1/bd/sd_fat32_controller/ip/sd_fat32_controller_dlmb_v10_0/sd_fat32_controller_dlmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all d:/FPGA/Trash/sd_fat32_2.0/sd_fat32_2.0.srcs/sources_1/bd/sd_fat32_controller/ip/sd_fat32_controller_dlmb_v10_0/sd_fat32_controller_dlmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/FPGA/Trash/sd_fat32_2.0/sd_fat32_2.0.srcs/sources_1/bd/sd_fat32_controller/ip/sd_fat32_controller_ilmb_v10_0/sd_fat32_controller_ilmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all d:/FPGA/Trash/sd_fat32_2.0/sd_fat32_2.0.srcs/sources_1/bd/sd_fat32_controller/ip/sd_fat32_controller_ilmb_v10_0/sd_fat32_controller_ilmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/FPGA/Trash/sd_fat32_2.0/sd_fat32_2.0.srcs/sources_1/bd/sd_fat32_controller/ip/sd_fat32_controller_dlmb_bram_if_cntlr_0/sd_fat32_controller_dlmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/FPGA/Trash/sd_fat32_2.0/sd_fat32_2.0.srcs/sources_1/bd/sd_fat32_controller/ip/sd_fat32_controller_ilmb_bram_if_cntlr_0/sd_fat32_controller_ilmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/FPGA/Trash/sd_fat32_2.0/sd_fat32_2.0.srcs/sources_1/bd/sd_fat32_controller/ip/sd_fat32_controller_lmb_bram_0/sd_fat32_controller_lmb_bram_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/FPGA/Trash/sd_fat32_2.0/sd_fat32_2.0.srcs/sources_1/bd/sd_fat32_controller/ip/sd_fat32_controller_mdm_1_0/sd_fat32_controller_mdm_1_0.xdc]
set_property used_in_implementation false [get_files -all d:/FPGA/Trash/sd_fat32_2.0/sd_fat32_2.0.srcs/sources_1/bd/sd_fat32_controller/ip/sd_fat32_controller_mdm_1_0/sd_fat32_controller_mdm_1_0_ooc_trace.xdc]
set_property used_in_implementation false [get_files -all d:/FPGA/Trash/sd_fat32_2.0/sd_fat32_2.0.srcs/sources_1/bd/sd_fat32_controller/ip/sd_fat32_controller_rst_clk_wiz_0_100M_0/sd_fat32_controller_rst_clk_wiz_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/FPGA/Trash/sd_fat32_2.0/sd_fat32_2.0.srcs/sources_1/bd/sd_fat32_controller/ip/sd_fat32_controller_rst_clk_wiz_0_100M_0/sd_fat32_controller_rst_clk_wiz_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all d:/FPGA/Trash/sd_fat32_2.0/sd_fat32_2.0.srcs/sources_1/bd/sd_fat32_controller/ip/sd_fat32_controller_rst_clk_wiz_0_100M_0/sd_fat32_controller_rst_clk_wiz_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/FPGA/Trash/sd_fat32_2.0/sd_fat32_2.0.srcs/sources_1/bd/sd_fat32_controller/ip/sd_fat32_controller_xbar_0/sd_fat32_controller_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/FPGA/Trash/sd_fat32_2.0/sd_fat32_2.0.srcs/sources_1/bd/sd_fat32_controller/ip/sd_fat32_controller_rst_mig_7series_0_75M_0/sd_fat32_controller_rst_mig_7series_0_75M_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/FPGA/Trash/sd_fat32_2.0/sd_fat32_2.0.srcs/sources_1/bd/sd_fat32_controller/ip/sd_fat32_controller_rst_mig_7series_0_75M_0/sd_fat32_controller_rst_mig_7series_0_75M_0.xdc]
set_property used_in_implementation false [get_files -all d:/FPGA/Trash/sd_fat32_2.0/sd_fat32_2.0.srcs/sources_1/bd/sd_fat32_controller/ip/sd_fat32_controller_rst_mig_7series_0_75M_0/sd_fat32_controller_rst_mig_7series_0_75M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/FPGA/Trash/sd_fat32_2.0/sd_fat32_2.0.srcs/sources_1/bd/sd_fat32_controller/ip/sd_fat32_controller_xbar_1/sd_fat32_controller_xbar_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/FPGA/Trash/sd_fat32_2.0/sd_fat32_2.0.srcs/sources_1/bd/sd_fat32_controller/ip/sd_fat32_controller_PmodSD_0_1/sd_fat32_controller_PmodSD_0_1_board.xdc]
set_property used_in_implementation false [get_files -all d:/FPGA/Trash/sd_fat32_2.0/sd_fat32_2.0.srcs/sources_1/bd/sd_fat32_controller/ip/sd_fat32_controller_PmodSD_0_1/src/PmodSD_axi_gpio_0_0/PmodSD_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/FPGA/Trash/sd_fat32_2.0/sd_fat32_2.0.srcs/sources_1/bd/sd_fat32_controller/ip/sd_fat32_controller_PmodSD_0_1/src/PmodSD_axi_gpio_0_0/PmodSD_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/FPGA/Trash/sd_fat32_2.0/sd_fat32_2.0.srcs/sources_1/bd/sd_fat32_controller/ip/sd_fat32_controller_PmodSD_0_1/src/PmodSD_axi_gpio_0_0/PmodSD_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/FPGA/Trash/sd_fat32_2.0/sd_fat32_2.0.srcs/sources_1/bd/sd_fat32_controller/ip/sd_fat32_controller_PmodSD_0_1/src/PmodSD_axi_quad_spi_0_0/PmodSD_axi_quad_spi_0_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/FPGA/Trash/sd_fat32_2.0/sd_fat32_2.0.srcs/sources_1/bd/sd_fat32_controller/ip/sd_fat32_controller_PmodSD_0_1/src/PmodSD_axi_quad_spi_0_0/PmodSD_axi_quad_spi_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/FPGA/Trash/sd_fat32_2.0/sd_fat32_2.0.srcs/sources_1/bd/sd_fat32_controller/ip/sd_fat32_controller_PmodSD_0_1/src/PmodSD_axi_quad_spi_0_0/PmodSD_axi_quad_spi_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/FPGA/Trash/sd_fat32_2.0/sd_fat32_2.0.srcs/sources_1/bd/sd_fat32_controller/ip/sd_fat32_controller_PmodSD_0_1/src/PmodSD_axi_quad_spi_0_0/PmodSD_axi_quad_spi_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/FPGA/Trash/sd_fat32_2.0/sd_fat32_2.0.srcs/sources_1/bd/sd_fat32_controller/ip/sd_fat32_controller_PmodSD_0_1/src/PmodSD_pmod_bridge_0_0/PmodSD_pmod_bridge_0_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/FPGA/Trash/sd_fat32_2.0/sd_fat32_2.0.srcs/sources_1/bd/sd_fat32_controller/ip/sd_fat32_controller_PmodSD_0_1/src/PmodSD_pmod_bridge_0_0/src/pmod_concat_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/FPGA/Trash/sd_fat32_2.0/sd_fat32_2.0.srcs/sources_1/bd/sd_fat32_controller/ip/sd_fat32_controller_PmodSD_0_1/src/PmodSD_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/FPGA/Trash/sd_fat32_2.0/sd_fat32_2.0.srcs/sources_1/bd/sd_fat32_controller/ip/sd_fat32_controller_auto_cc_0/sd_fat32_controller_auto_cc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/FPGA/Trash/sd_fat32_2.0/sd_fat32_2.0.srcs/sources_1/bd/sd_fat32_controller/ip/sd_fat32_controller_auto_cc_0/sd_fat32_controller_auto_cc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/FPGA/Trash/sd_fat32_2.0/sd_fat32_2.0.srcs/sources_1/bd/sd_fat32_controller/ip/sd_fat32_controller_auto_us_0/sd_fat32_controller_auto_us_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/FPGA/Trash/sd_fat32_2.0/sd_fat32_2.0.srcs/sources_1/bd/sd_fat32_controller/ip/sd_fat32_controller_auto_us_0/sd_fat32_controller_auto_us_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/FPGA/Trash/sd_fat32_2.0/sd_fat32_2.0.srcs/sources_1/bd/sd_fat32_controller/ip/sd_fat32_controller_auto_us_1/sd_fat32_controller_auto_us_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/FPGA/Trash/sd_fat32_2.0/sd_fat32_2.0.srcs/sources_1/bd/sd_fat32_controller/ip/sd_fat32_controller_auto_us_1/sd_fat32_controller_auto_us_1_clocks.xdc]
set_property used_in_implementation false [get_files -all D:/FPGA/Trash/sd_fat32_2.0/sd_fat32_2.0.srcs/sources_1/bd/sd_fat32_controller/sd_fat32_controller_ooc.xdc]
set_property is_locked true [get_files D:/FPGA/Trash/sd_fat32_2.0/sd_fat32_2.0.srcs/sources_1/bd/sd_fat32_controller/sd_fat32_controller.bd]

read_verilog -library xil_defaultlib D:/FPGA/Trash/sd_fat32_2.0/sd_fat32_2.0.srcs/sources_1/bd/sd_fat32_controller/hdl/sd_fat32_controller_wrapper.v
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
synth_design -top sd_fat32_controller_wrapper -part xc7a100tcsg324-1
write_checkpoint -noxdef sd_fat32_controller_wrapper.dcp
catch { report_utilization -file sd_fat32_controller_wrapper_utilization_synth.rpt -pb sd_fat32_controller_wrapper_utilization_synth.pb }
