# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/FPGA/Projects/i2c_priem_datchik_40byte/i2c_priem_datchik_40byte_2.0.cache/wt [current_project]
set_property parent.project_path D:/FPGA/Projects/i2c_priem_datchik_40byte/i2c_priem_datchik_40byte_2.0.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:nexys-a7-100t:part0:1.0 [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_verilog -library xil_defaultlib D:/FPGA/Projects/i2c_priem_datchik_40byte/i2c_priem_datchik_40byte_2.0.srcs/sources_1/new/i2c_40byte.v
read_xdc D:/FPGA/Projects/i2c_priem_datchik_40byte/i2c_priem_datchik_40byte_2.0.srcs/constrs_1/imports/FPGA/Nexys-A7-100T-Master.xdc
set_property used_in_implementation false [get_files D:/FPGA/Projects/i2c_priem_datchik_40byte/i2c_priem_datchik_40byte_2.0.srcs/constrs_1/imports/FPGA/Nexys-A7-100T-Master.xdc]

synth_design -top i2c_40byte -part xc7a100tcsg324-1
write_checkpoint -noxdef i2c_40byte.dcp
catch { report_utilization -file i2c_40byte_utilization_synth.rpt -pb i2c_40byte_utilization_synth.pb }
