# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: D:/Bakytzhan/FPGA/Nexys4_Master.xdc

# Block Designs: bd/calc_check/calc_check.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==calc_check || ORIG_REF_NAME==calc_check} -quiet] -quiet

# IP: bd/calc_check/ip/calc_check_floating_point_0_0/calc_check_floating_point_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==calc_check_floating_point_0_0 || ORIG_REF_NAME==calc_check_floating_point_0_0} -quiet] -quiet

# IP: bd/calc_check/ip/calc_check_floating_point_0_1/calc_check_floating_point_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==calc_check_floating_point_0_1 || ORIG_REF_NAME==calc_check_floating_point_0_1} -quiet] -quiet

# IP: bd/calc_check/ip/calc_check_floating_point_0_2/calc_check_floating_point_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==calc_check_floating_point_0_2 || ORIG_REF_NAME==calc_check_floating_point_0_2} -quiet] -quiet

# Block Designs: bd/calculation/calculation.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==calculation || ORIG_REF_NAME==calculation} -quiet] -quiet

# IP: bd/calculation/ip/calculation_floating_point_0_0/calculation_floating_point_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==calculation_floating_point_0_0 || ORIG_REF_NAME==calculation_floating_point_0_0} -quiet] -quiet

# IP: bd/calculation/ip/calculation_floating_point_1_0/calculation_floating_point_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==calculation_floating_point_1_0 || ORIG_REF_NAME==calculation_floating_point_1_0} -quiet] -quiet

# IP: bd/calculation/ip/calculation_floating_point_2_0/calculation_floating_point_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==calculation_floating_point_2_0 || ORIG_REF_NAME==calculation_floating_point_2_0} -quiet] -quiet

# XDC: bd/calc_check/calc_check_ooc.xdc

# XDC: bd/calculation/calculation_ooc.xdc
