# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/FPGA/Nexys4_Master.xdc

# Block Designs: bd/calc/calc.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==calc || ORIG_REF_NAME==calc}]

# IP: bd/calc/ip/calc_floating_point_0_0/calc_floating_point_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==calc_floating_point_0_0 || ORIG_REF_NAME==calc_floating_point_0_0}]

# IP: bd/calc/ip/calc_floating_point_1_0/calc_floating_point_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==calc_floating_point_1_0 || ORIG_REF_NAME==calc_floating_point_1_0}]

# IP: bd/calc/ip/calc_floating_point_2_0/calc_floating_point_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==calc_floating_point_2_0 || ORIG_REF_NAME==calc_floating_point_2_0}]

# IP: ip/fifo_generator_0/fifo_generator_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fifo_generator_0 || ORIG_REF_NAME==fifo_generator_0}]

# IPX: ip/fifo_generator_0.xcix
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fifo_generator_0 || ORIG_REF_NAME==fifo_generator_0}]

# XDC: bd/calc/ip/calc_floating_point_0_0/calc_floating_point_0_0_ooc.xdc

# XDC: bd/calc/ip/calc_floating_point_1_0/calc_floating_point_1_0_ooc.xdc

# XDC: bd/calc/ip/calc_floating_point_2_0/calc_floating_point_2_0_ooc.xdc

# XDC: bd/calc/calc_ooc.xdc

# XDC: ip/fifo_generator_0/fifo_generator_0/fifo_generator_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_generator_0 || ORIG_REF_NAME==fifo_generator_0}] {/U0 }]/U0 ]]

# XDC: ip/fifo_generator_0/fifo_generator_0/fifo_generator_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_generator_0 || ORIG_REF_NAME==fifo_generator_0}] {/U0 }]/U0 ]]
