#!/bin/bash -f
# Vivado (TM) v2015.4 (64-bit)
#
# Filename    : sd_fat32_controller.sh
# Simulator   : Cadence Incisive Enterprise Simulator
# Description : Simulation script for compiling, elaborating and verifying the project source files.
#               The script will automatically create the design libraries sub-directories in the run
#               directory, add the library logical mappings in the simulator setup file, create default
#               'do/prj' file, execute compilation, elaboration and simulation steps.
#
# Generated by Vivado on Sun Jan 27 14:08:17 +0600 2019
# IP Build 1412160 on Tue Nov 17 13:47:24 MST 2015 
#
# usage: sd_fat32_controller.sh [-help]
# usage: sd_fat32_controller.sh [-lib_map_path]
# usage: sd_fat32_controller.sh [-noclean_files]
# usage: sd_fat32_controller.sh [-reset_run]
#
# Prerequisite:- To compile and run simulation, you must compile the Xilinx simulation libraries using the
# 'compile_simlib' TCL command. For more information about this command, run 'compile_simlib -help' in the
# Vivado Tcl Shell. Once the libraries have been compiled successfully, specify the -lib_map_path switch
# that points to these libraries and rerun export_simulation. For more information about this switch please
# type 'export_simulation -help' in the Tcl shell.
#
# You can also point to the simulation libraries by either replacing the <SPECIFY_COMPILED_LIB_PATH> in this
# script with the compiled library directory path or specify this path with the '-lib_map_path' switch when
# executing this script. Please type 'sd_fat32_controller.sh -help' for more information.
#
# Additional references - 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
# ********************************************************************************************************

# Script info
echo -e "sd_fat32_controller.sh - Script generated by export_simulation (Vivado v2015.4 (64-bit)-id)\n"

# Script usage
usage()
{
  msg="Usage: sd_fat32_controller.sh [-help]\n\
Usage: sd_fat32_controller.sh [-lib_map_path]\n\
Usage: sd_fat32_controller.sh [-reset_run]\n\
Usage: sd_fat32_controller.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}

if [[ ($# == 1 ) && ($1 != "-lib_map_path" && $1 != "-noclean_files" && $1 != "-reset_run" && $1 != "-help" && $1 != "-h") ]]; then
  echo -e "ERROR: Unknown option specified '$1' (type \"./sd_fat32_controller.sh -help\" for more information)\n"
  exit 1
fi

if [[ ($1 == "-help" || $1 == "-h") ]]; then
  usage
fi

# STEP: setup
setup()
{
  case $1 in
    "-lib_map_path" )
      if [[ ($2 == "") ]]; then
        echo -e "ERROR: Simulation library directory path not specified (type \"./sd_fat32_controller.sh -help\" for more information)\n"
        exit 1
      fi
      # precompiled simulation library directory path
     create_lib_mappings $2
     touch hdl.var
    ;;
    "-reset_run" )
      reset_run
      echo -e "INFO: Simulation run files deleted.\n"
      exit 0
    ;;
    "-noclean_files" )
      # do not remove previous data
    ;;
    * )
     create_lib_mappings $2
     touch hdl.var
  esac

  # Add any setup/initialization commands here:-

  # <user specific commands>

}

# Remove generated data from the previous run and re-create setup files/library mappings
reset_run()
{
  files_to_remove=(ncsim.key irun.key ncvlog.log ncvhdl.log compile.log elaborate.log simulate.log run.log waves.shm INCA_libs)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done
}

# Main steps
run()
{
  setup $1 $2
  compile
  elaborate
  simulate
}

# Create design library directory paths and define design library mappings in cds.lib
create_lib_mappings()
{
  libs=(xil_defaultlib axi_lite_ipif_v3_0_3 lib_pkg_v1_0_2 lib_srl_fifo_v1_0_2 lib_cdc_v1_0_2 axi_uartlite_v2_0_10 microblaze_v9_5_3 lmb_v10_v3_0_7 lmb_bram_if_cntlr_v4_0_7 blk_mem_gen_v8_3_1 axi_intc_v4_1_5 mdm_v3_2_4 proc_sys_reset_v5_0_8 dist_mem_gen_v8_0_9 fifo_generator_v13_0_1 lib_fifo_v1_0_4 interrupt_control_v3_1_3 axi_quad_spi_v3_2_6 axi_gpio_v2_0_9 axi_timer_v2_0_8 generic_baseblocks_v2_1_0 axi_infrastructure_v1_1_0 axi_register_slice_v2_1_7 axi_data_fifo_v2_1_6 axi_crossbar_v2_1_8 axi_clock_converter_v2_1_6 axi_protocol_converter_v2_1_7 axi_dwidth_converter_v2_1_7)
  file="cds.lib"
  dir="ies"

  if [[ -e $file ]]; then
    rm -f $file
  fi

  if [[ -e $dir ]]; then
    rm -rf $dir
  fi

  touch $file
  lib_map_path="<SPECIFY_COMPILED_LIB_PATH>"
  if [[ ($1 != "" && -e $1) ]]; then
    lib_map_path="$1"
  else
    echo -e "ERROR: Compiled simulation library directory path not specified or does not exist (type "./top.sh -help" for more information)\n"
  fi
  incl_ref="INCLUDE $lib_map_path/cds.lib"
  echo $incl_ref >> $file

  for (( i=0; i<${#libs[*]}; i++ )); do
    lib="${libs[i]}"
    lib_dir="$dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
      mapping="DEFINE $lib $dir/$lib"
      echo $mapping >> $file
    fi
  done
}


# RUN_STEP: <compile>
compile()
{
  # Directory path for design sources and include directories (if any) wrt this path
  ref_dir="."
  # Command line options
  opts_ver="-64bit -messages -logfile ncvlog.log -append_log"
  opts_vhd="-64bit -V93 -RELAX -logfile ncvhdl.log -append_log"

  # Compile design files
  ncvlog -work xil_defaultlib $opts_ver +incdir+"$ref_dir/../../../ipstatic/axi_infrastructure_v1_1/hdl/verilog" \
    "$ref_dir/../../../bd/sd_fat32_controller/hdl/sd_fat32_controller.v" \
    "$ref_dir/../../../bd/sd_fat32_controller/ip/sd_fat32_controller_mig_7series_0_1/sd_fat32_controller_mig_7series_0_1/user_design/rtl/axi/mig_7series_v2_4_axi_ctrl_addr_decode.v" \
    "$ref_dir/../../../bd/sd_fat32_controller/ip/sd_fat32_controller_mig_7series_0_1/sd_fat32_controller_mig_7series_0_1/user_design/rtl/axi/mig_7series_v2_4_axi_ctrl_read.v" \
    "$ref_dir/../../../bd/sd_fat32_controller/ip/sd_fat32_controller_mig_7series_0_1/sd_fat32_controller_mig_7series_0_1/user_design/rtl/axi/mig_7series_v2_4_axi_ctrl_reg.v" \
    "$ref_dir/../../../bd/sd_fat32_controller/ip/sd_fat32_controller_mig_7series_0_1/sd_fat32_controller_mig_7series_0_1/user_design/rtl/axi/mig_7series_v2_4_axi_ctrl_reg_bank.v" \
    "$ref_dir/../../../bd/sd_fat32_controller/ip/sd_fat32_controller_mig_7series_0_1/sd_fat32_controller_mig_7series_0_1/user_design/rtl/axi/mig_7series_v2_4_axi_ctrl_top.v" \
    "$ref_dir/../../../bd/sd_fat32_controller/ip/sd_fat32_controller_mig_7series_0_1/sd_fat32_controller_mig_7series_0_1/user_design/rtl/axi/mig_7series_v2_4_axi_ctrl_write.v" \
    "$ref_dir/../../../bd/sd_fat32_controller/ip/sd_fat32_controller_mig_7series_0_1/sd_fat32_controller_mig_7series_0_1/user_design/rtl/axi/mig_7series_v2_4_axi_mc.v" \
    "$ref_dir/../../../bd/sd_fat32_controller/ip/sd_fat32_controller_mig_7series_0_1/sd_fat32_controller_mig_7series_0_1/user_design/rtl/axi/mig_7series_v2_4_axi_mc_ar_channel.v" \
    "$ref_dir/../../../bd/sd_fat32_controller/ip/sd_fat32_controller_mig_7series_0_1/sd_fat32_controller_mig_7series_0_1/user_design/rtl/axi/mig_7series_v2_4_axi_mc_aw_channel.v" \
    "$ref_dir/../../../bd/sd_fat32_controller/ip/sd_fat32_controller_mig_7series_0_1/sd_fat32_controller_mig_7series_0_1/user_design/rtl/axi/mig_7series_v2_4_axi_mc_b_channel.v" \
    "$ref_dir/../../../bd/sd_fat32_controller/ip/sd_fat32_controller_mig_7series_0_1/sd_fat32_controller_mig_7series_0_1/user_design/rtl/axi/mig_7series_v2_4_axi_mc_cmd_arbiter.v" \
    "$ref_dir/../../../bd/sd_fat32_controller/ip/sd_fat32_controller_mig_7series_0_1/sd_fat32_controller_mig_7series_0_1/user_design/rtl/axi/mig_7series_v2_4_axi_mc_cmd_fsm.v" \
    "$ref_dir/../../../bd/sd_fat32_controller/ip/sd_fat32_controller_mig_7series_0_1/sd_fat32_controller_mig_7series_0_1/user_design/rtl/axi/mig_7series_v2_4_axi_mc_cmd_translator.v" \
    "$ref_dir/../../../bd/sd_fat32_controller/ip/sd_fat32_controller_mig_7series_0_1/sd_fat32_controller_mig_7series_0_1/user_design/rtl/axi/mig_7series_v2_4_axi_mc_fifo.v" \
    "$ref_dir/../../../bd/sd_fat32_controller/ip/sd_fat32_controller_mig_7series_0_1/sd_fat32_controller_mig_7series_0_1/user_design/rtl/axi/mig_7series_v2_4_axi_mc_incr_cmd.v" \
    "$ref_dir/../../../bd/sd_fat32_controller/ip/sd_fat32_controller_mig_7series_0_1/sd_fat32_controller_mig_7series_0_1/user_design/rtl/axi/mig_7series_v2_4_axi_mc_r_channel.v" \
    "$ref_dir/../../../bd/sd_fat32_controller/ip/sd_fat32_controller_mig_7series_0_1/sd_fat32_controller_mig_7series_0_1/user_design/rtl/axi/mig_7series_v2_4_axi_mc_simple_fifo.v" \
    "$ref_dir/../../../bd/sd_fat32_controller/ip/sd_fat32_controller_mig_7series_0_1/sd_fat32_controller_mig_7series_0_1/user_design/rtl/axi/mig_7series_v2_4_axi_mc_wrap_cmd.v" \
    "$ref_dir/../../../bd/sd_fat32_controller/ip/sd_fat32_controller_mig_7series_0_1/sd_fat32_controller_mig_7series_0_1/user_design/rtl/axi/mig_7series_v2_4_axi_mc_wr_cmd_fsm.v" \
    "$ref_dir/../../../bd/sd_fat32_controller/ip/sd_fat32_controller_mig_7series_0_1/sd_fat32_controller_mig_7series_0_1/user_design/rtl/axi/mig_7series_v2_4_axi_mc_w_channel.v" \
    "$ref_dir/../../../bd/sd_fat32_controller/ip/sd_fat32_controller_mig_7series_0_1/sd_fat32_controller_mig_7series_0_1/user_design/rtl/axi/mig_7series_v2_4_ddr_axic_register_slice.v" \
    "$ref_dir/../../../bd/sd_fat32_controller/ip/sd_fat32_controller_mig_7series_0_1/sd_fat32_controller_mig_7series_0_1/user_design/rtl/axi/mig_7series_v2_4_ddr_axi_register_slice.v" \
    "$ref_dir/../../../bd/sd_fat32_controller/ip/sd_fat32_controller_mig_7series_0_1/sd_fat32_controller_mig_7series_0_1/user_design/rtl/axi/mig_7series_v2_4_ddr_axi_upsizer.v" \
    "$ref_dir/../../../bd/sd_fat32_controller/ip/sd_fat32_controller_mig_7series_0_1/sd_fat32_controller_mig_7series_0_1/user_design/rtl/axi/mig_7series_v2_4_ddr_a_upsizer.v" \
    "$ref_dir/../../../bd/sd_fat32_controller/ip/sd_fat32_controller_mig_7series_0_1/sd_fat32_controller_mig_7series_0_1/user_design/rtl/axi/mig_7series_v2_4_ddr_carry_and.v" \
    "$ref_dir/../../../bd/sd_fat32_controller/ip/sd_fat32_controller_mig_7series_0_1/sd_fat32_controller_mig_7series_0_1/user_design/rtl/axi/mig_7series_v2_4_ddr_carry_latch_and.v" \
    "$ref_dir/../../../bd/sd_fat32_controller/ip/sd_fat32_controller_mig_7series_0_1/sd_fat32_controller_mig_7series_0_1/user_design/rtl/axi/mig_7series_v2_4_ddr_carry_latch_or.v" \
    "$ref_dir/../../../bd/sd_fat32_controller/ip/sd_fat32_controller_mig_7series_0_1/sd_fat32_controller_mig_7series_0_1/user_design/rtl/axi/mig_7series_v2_4_ddr_carry_or.v" \
    "$ref_dir/../../../bd/sd_fat32_controller/ip/sd_fat32_controller_mig_7series_0_1/sd_fat32_controller_mig_7series_0_1/user_design/rtl/axi/mig_7series_v2_4_ddr_command_fifo.v" \
    "$ref_dir/../../../bd/sd_fat32_controller/ip/sd_fat32_controller_mig_7series_0_1/sd_fat32_controller_mig_7series_0_1/user_design/rtl/axi/mig_7series_v2_4_ddr_comparator.v" \
    "$ref_dir/../../../bd/sd_fat32_controller/ip/sd_fat32_controller_mig_7series_0_1/sd_fat32_controller_mig_7series_0_1/user_design/rtl/axi/mig_7series_v2_4_ddr_comparator_sel.v" \
    "$ref_dir/../../../bd/sd_fat32_controller/ip/sd_fat32_controller_mig_7series_0_1/sd_fat32_controller_mig_7series_0_1/user_design/rtl/axi/mig_7series_v2_4_ddr_comparator_sel_static.v" \
    "$ref_dir/../../../bd/sd_fat32_controller/ip/sd_fat32_controller_mig_7series_0_1/sd_fat32_controller_mig_7series_0_1/user_design/rtl/axi/mig_7series_v2_4_ddr_r_upsizer.v" \
    "$ref_dir/../../../bd/sd_fat32_controller/ip/sd_fat32_controller_mig_7series_0_1/sd_fat32_controller_mig_7series_0_1/user_design/rtl/axi/mig_7series_v2_4_ddr_w_upsizer.v" \
    "$ref_dir/../../../bd/sd_fat32_controller/ip/sd_fat32_controller_mig_7series_0_1/sd_fat32_controller_mig_7series_0_1/user_design/rtl/clocking/mig_7series_v2_4_clk_ibuf.v" \
    "$ref_dir/../../../bd/sd_fat32_controller/ip/sd_fat32_controller_mig_7series_0_1/sd_fat32_controller_mig_7series_0_1/user_design/rtl/clocking/mig_7series_v2_4_infrastructure.v" \
    "$ref_dir/../../../bd/sd_fat32_controller/ip/sd_fat32_controller_mig_7series_0_1/sd_fat32_controller_mig_7series_0_1/user_design/rtl/clocking/mig_7series_v2_4_iodelay_ctrl.v" \
    "$ref_dir/../../../bd/sd_fat32_controller/ip/sd_fat32_controller_mig_7series_0_1/sd_fat32_controller_mig_7series_0_1/user_design/rtl/clocking/mig_7series_v2_4_tempmon.v" \
    "$ref_dir/../../../bd/sd_fat32_controller/ip/sd_fat32_controller_mig_7series_0_1/sd_fat32_controller_mig_7series_0_1/user_design/rtl/controller/mig_7series_v2_4_arb_mux.v" \
    "$ref_dir/../../../bd/sd_fat32_controller/ip/sd_fat32_controller_mig_7series_0_1/sd_fat32_controller_mig_7series_0_1/user_design/rtl/controller/mig_7series_v2_4_arb_row_col.v" \
    "$ref_dir/../../../bd/sd_fat32_controller/ip/sd_fat32_controller_mig_7series_0_1/sd_fat32_controller_mig_7series_0_1/user_design/rtl/controller/mig_7series_v2_4_arb_select.v" \
    "$ref_dir/../../../bd/sd_fat32_controller/ip/sd_fat32_controller_mig_7series_0_1/sd_fat32_controller_mig_7series_0_1/user_design/rtl/controller/mig_7series_v2_4_bank_cntrl.v" \
    "$ref_dir/../../../bd/sd_fat32_controller/ip/sd_fat32_controller_mig_7series_0_1/sd_fat32_controller_mig_7series_0_1/user_design/rtl/controller/mig_7series_v2_4_bank_common.v" \
    "$ref_dir/../../../bd/sd_fat32_controller/ip/sd_fat32_controller_mig_7series_0_1/sd_fat32_controller_mig_7series_0_1/user_design/rtl/controller/mig_7series_v2_4_bank_compare.v" \
    "$ref_dir/../../../bd/sd_fat32_controller/ip/sd_fat32_controller_mig_7series_0_1/sd_fat32_controller_mig_7series_0_1/user_design/rtl/controller/mig_7series_v2_4_bank_mach.v" \
    "$ref_dir/../../../bd/sd_fat32_controller/ip/sd_fat32_controller_mig_7series_0_1/sd_fat32_controller_mig_7series_0_1/user_design/rtl/controller/mig_7series_v2_4_bank_queue.v" \
    "$ref_dir/../../../bd/sd_fat32_controller/ip/sd_fat32_controller_mig_7series_0_1/sd_fat32_controller_mig_7series_0_1/user_design/rtl/controller/mig_7series_v2_4_bank_state.v" \
    "$ref_dir/../../../bd/sd_fat32_controller/ip/sd_fat32_controller_mig_7series_0_1/sd_fat32_controller_mig_7series_0_1/user_design/rtl/controller/mig_7series_v2_4_col_mach.v" \
    "$ref_dir/../../../bd/sd_fat32_controller/ip/sd_fat32_controller_mig_7series_0_1/sd_fat32_controller_mig_7series_0_1/user_design/rtl/controller/mig_7series_v2_4_mc.v" \
    "$ref_dir/../../../bd/sd_fat32_controller/ip/sd_fat32_controller_mig_7series_0_1/sd_fat32_controller_mig_7series_0_1/user_design/rtl/controller/mig_7series_v2_4_rank_cntrl.v" \
    "$ref_dir/../../../bd/sd_fat32_controller/ip/sd_fat32_controller_mig_7series_0_1/sd_fat32_controller_mig_7series_0_1/user_design/rtl/controller/mig_7series_v2_4_rank_common.v" \
    "$ref_dir/../../../bd/sd_fat32_controller/ip/sd_fat32_controller_mig_7series_0_1/sd_fat32_controller_mig_7series_0_1/user_design/rtl/controller/mig_7series_v2_4_rank_mach.v" \
    "$ref_dir/../../../bd/sd_fat32_controller/ip/sd_fat32_controller_mig_7series_0_1/sd_fat32_controller_mig_7series_0_1/user_design/rtl/controller/mig_7series_v2_4_round_robin_arb.v" \
    "$ref_dir/../../../bd/sd_fat32_controller/ip/sd_fat32_controller_mig_7series_0_1/sd_fat32_controller_mig_7series_0_1/user_design/rtl/ecc/mig_7series_v2_4_ecc_buf.v" \
    "$ref_dir/../../../bd/sd_fat32_controller/ip/sd_fat32_controller_mig_7series_0_1/sd_fat32_controller_mig_7series_0_1/user_design/rtl/ecc/mig_7series_v2_4_ecc_dec_fix.v" \
    "$ref_dir/../../../bd/sd_fat32_controller/ip/sd_fat32_controller_mig_7series_0_1/sd_fat32_controller_mig_7series_0_1/user_design/rtl/ecc/mig_7series_v2_4_ecc_gen.v" \
    "$ref_dir/../../../bd/sd_fat32_controller/ip/sd_fat32_controller_mig_7series_0_1/sd_fat32_controller_mig_7series_0_1/user_design/rtl/ecc/mig_7series_v2_4_ecc_merge_enc.v" \
    "$ref_dir/../../../bd/sd_fat32_controller/ip/sd_fat32_controller_mig_7series_0_1/sd_fat32_controller_mig_7series_0_1/user_design/rtl/ecc/mig_7series_v2_4_fi_xor.v" \
    "$ref_dir/../../../bd/sd_fat32_controller/ip/sd_fat32_controller_mig_7series_0_1/sd_fat32_controller_mig_7series_0_1/user_design/rtl/ip_top/mig_7series_v2_4_memc_ui_top_axi.v" \
    "$ref_dir/../../../bd/sd_fat32_controller/ip/sd_fat32_controller_mig_7series_0_1/sd_fat32_controller_mig_7series_0_1/user_design/rtl/ip_top/mig_7series_v2_4_mem_intfc.v" \
    "$ref_dir/../../../bd/sd_fat32_controller/ip/sd_fat32_controller_mig_7series_0_1/sd_fat32_controller_mig_7series_0_1/user_design/rtl/phy/mig_7series_v2_4_ddr_byte_group_io.v" \
    "$ref_dir/../../../bd/sd_fat32_controller/ip/sd_fat32_controller_mig_7series_0_1/sd_fat32_controller_mig_7series_0_1/user_design/rtl/phy/mig_7series_v2_4_ddr_byte_lane.v" \
    "$ref_dir/../../../bd/sd_fat32_controller/ip/sd_fat32_controller_mig_7series_0_1/sd_fat32_controller_mig_7series_0_1/user_design/rtl/phy/mig_7series_v2_4_ddr_calib_top.v" \
    "$ref_dir/../../../bd/sd_fat32_controller/ip/sd_fat32_controller_mig_7series_0_1/sd_fat32_controller_mig_7series_0_1/user_design/rtl/phy/mig_7series_v2_4_ddr_if_post_fifo.v" \
    "$ref_dir/../../../bd/sd_fat32_controller/ip/sd_fat32_controller_mig_7series_0_1/sd_fat32_controller_mig_7series_0_1/user_design/rtl/phy/mig_7series_v2_4_ddr_mc_phy.v" \
    "$ref_dir/../../../bd/sd_fat32_controller/ip/sd_fat32_controller_mig_7series_0_1/sd_fat32_controller_mig_7series_0_1/user_design/rtl/phy/mig_7series_v2_4_ddr_mc_phy_wrapper.v" \
    "$ref_dir/../../../bd/sd_fat32_controller/ip/sd_fat32_controller_mig_7series_0_1/sd_fat32_controller_mig_7series_0_1/user_design/rtl/phy/mig_7series_v2_4_ddr_of_pre_fifo.v" \
    "$ref_dir/../../../bd/sd_fat32_controller/ip/sd_fat32_controller_mig_7series_0_1/sd_fat32_controller_mig_7series_0_1/user_design/rtl/phy/mig_7series_v2_4_ddr_phy_4lanes.v" \
    "$ref_dir/../../../bd/sd_fat32_controller/ip/sd_fat32_controller_mig_7series_0_1/sd_fat32_controller_mig_7series_0_1/user_design/rtl/phy/mig_7series_v2_4_ddr_phy_ck_addr_cmd_delay.v" \
    "$ref_dir/../../../bd/sd_fat32_controller/ip/sd_fat32_controller_mig_7series_0_1/sd_fat32_controller_mig_7series_0_1/user_design/rtl/phy/mig_7series_v2_4_ddr_phy_dqs_found_cal.v" \
    "$ref_dir/../../../bd/sd_fat32_controller/ip/sd_fat32_controller_mig_7series_0_1/sd_fat32_controller_mig_7series_0_1/user_design/rtl/phy/mig_7series_v2_4_ddr_phy_dqs_found_cal_hr.v" \
    "$ref_dir/../../../bd/sd_fat32_controller/ip/sd_fat32_controller_mig_7series_0_1/sd_fat32_controller_mig_7series_0_1/user_design/rtl/phy/mig_7series_v2_4_ddr_phy_init.v" \
    "$ref_dir/../../../bd/sd_fat32_controller/ip/sd_fat32_controller_mig_7series_0_1/sd_fat32_controller_mig_7series_0_1/user_design/rtl/phy/mig_7series_v2_4_ddr_phy_ocd_cntlr.v" \
    "$ref_dir/../../../bd/sd_fat32_controller/ip/sd_fat32_controller_mig_7series_0_1/sd_fat32_controller_mig_7series_0_1/user_design/rtl/phy/mig_7series_v2_4_ddr_phy_ocd_data.v" \
    "$ref_dir/../../../bd/sd_fat32_controller/ip/sd_fat32_controller_mig_7series_0_1/sd_fat32_controller_mig_7series_0_1/user_design/rtl/phy/mig_7series_v2_4_ddr_phy_ocd_edge.v" \
    "$ref_dir/../../../bd/sd_fat32_controller/ip/sd_fat32_controller_mig_7series_0_1/sd_fat32_controller_mig_7series_0_1/user_design/rtl/phy/mig_7series_v2_4_ddr_phy_ocd_lim.v" \
    "$ref_dir/../../../bd/sd_fat32_controller/ip/sd_fat32_controller_mig_7series_0_1/sd_fat32_controller_mig_7series_0_1/user_design/rtl/phy/mig_7series_v2_4_ddr_phy_ocd_mux.v" \
    "$ref_dir/../../../bd/sd_fat32_controller/ip/sd_fat32_controller_mig_7series_0_1/sd_fat32_controller_mig_7series_0_1/user_design/rtl/phy/mig_7series_v2_4_ddr_phy_ocd_po_cntlr.v" \
    "$ref_dir/../../../bd/sd_fat32_controller/ip/sd_fat32_controller_mig_7series_0_1/sd_fat32_controller_mig_7series_0_1/user_design/rtl/phy/mig_7series_v2_4_ddr_phy_ocd_samp.v" \
    "$ref_dir/../../../bd/sd_fat32_controller/ip/sd_fat32_controller_mig_7series_0_1/sd_fat32_controller_mig_7series_0_1/user_design/rtl/phy/mig_7series_v2_4_ddr_phy_oclkdelay_cal.v" \
    "$ref_dir/../../../bd/sd_fat32_controller/ip/sd_fat32_controller_mig_7series_0_1/sd_fat32_controller_mig_7series_0_1/user_design/rtl/phy/mig_7series_v2_4_ddr_phy_prbs_rdlvl.v" \
    "$ref_dir/../../../bd/sd_fat32_controller/ip/sd_fat32_controller_mig_7series_0_1/sd_fat32_controller_mig_7series_0_1/user_design/rtl/phy/mig_7series_v2_4_ddr_phy_rdlvl.v" \
    "$ref_dir/../../../bd/sd_fat32_controller/ip/sd_fat32_controller_mig_7series_0_1/sd_fat32_controller_mig_7series_0_1/user_design/rtl/phy/mig_7series_v2_4_ddr_phy_tempmon.v" \
    "$ref_dir/../../../bd/sd_fat32_controller/ip/sd_fat32_controller_mig_7series_0_1/sd_fat32_controller_mig_7series_0_1/user_design/rtl/phy/mig_7series_v2_4_ddr_phy_top.v" \
    "$ref_dir/../../../bd/sd_fat32_controller/ip/sd_fat32_controller_mig_7series_0_1/sd_fat32_controller_mig_7series_0_1/user_design/rtl/phy/mig_7series_v2_4_ddr_phy_wrcal.v" \
    "$ref_dir/../../../bd/sd_fat32_controller/ip/sd_fat32_controller_mig_7series_0_1/sd_fat32_controller_mig_7series_0_1/user_design/rtl/phy/mig_7series_v2_4_ddr_phy_wrlvl.v" \
    "$ref_dir/../../../bd/sd_fat32_controller/ip/sd_fat32_controller_mig_7series_0_1/sd_fat32_controller_mig_7series_0_1/user_design/rtl/phy/mig_7series_v2_4_ddr_phy_wrlvl_off_delay.v" \
    "$ref_dir/../../../bd/sd_fat32_controller/ip/sd_fat32_controller_mig_7series_0_1/sd_fat32_controller_mig_7series_0_1/user_design/rtl/phy/mig_7series_v2_4_ddr_prbs_gen.v" \
    "$ref_dir/../../../bd/sd_fat32_controller/ip/sd_fat32_controller_mig_7series_0_1/sd_fat32_controller_mig_7series_0_1/user_design/rtl/phy/mig_7series_v2_4_poc_cc.v" \
    "$ref_dir/../../../bd/sd_fat32_controller/ip/sd_fat32_controller_mig_7series_0_1/sd_fat32_controller_mig_7series_0_1/user_design/rtl/phy/mig_7series_v2_4_poc_edge_store.v" \
    "$ref_dir/../../../bd/sd_fat32_controller/ip/sd_fat32_controller_mig_7series_0_1/sd_fat32_controller_mig_7series_0_1/user_design/rtl/phy/mig_7series_v2_4_poc_meta.v" \
    "$ref_dir/../../../bd/sd_fat32_controller/ip/sd_fat32_controller_mig_7series_0_1/sd_fat32_controller_mig_7series_0_1/user_design/rtl/phy/mig_7series_v2_4_poc_pd.v" \
    "$ref_dir/../../../bd/sd_fat32_controller/ip/sd_fat32_controller_mig_7series_0_1/sd_fat32_controller_mig_7series_0_1/user_design/rtl/phy/mig_7series_v2_4_poc_tap_base.v" \
    "$ref_dir/../../../bd/sd_fat32_controller/ip/sd_fat32_controller_mig_7series_0_1/sd_fat32_controller_mig_7series_0_1/user_design/rtl/phy/mig_7series_v2_4_poc_top.v" \
    "$ref_dir/../../../bd/sd_fat32_controller/ip/sd_fat32_controller_mig_7series_0_1/sd_fat32_controller_mig_7series_0_1/user_design/rtl/ui/mig_7series_v2_4_ui_cmd.v" \
    "$ref_dir/../../../bd/sd_fat32_controller/ip/sd_fat32_controller_mig_7series_0_1/sd_fat32_controller_mig_7series_0_1/user_design/rtl/ui/mig_7series_v2_4_ui_rd_data.v" \
    "$ref_dir/../../../bd/sd_fat32_controller/ip/sd_fat32_controller_mig_7series_0_1/sd_fat32_controller_mig_7series_0_1/user_design/rtl/ui/mig_7series_v2_4_ui_top.v" \
    "$ref_dir/../../../bd/sd_fat32_controller/ip/sd_fat32_controller_mig_7series_0_1/sd_fat32_controller_mig_7series_0_1/user_design/rtl/ui/mig_7series_v2_4_ui_wr_data.v" \
    "$ref_dir/../../../bd/sd_fat32_controller/ip/sd_fat32_controller_mig_7series_0_1/sd_fat32_controller_mig_7series_0_1/user_design/rtl/sd_fat32_controller_mig_7series_0_1_mig_sim.v" \
    "$ref_dir/../../../bd/sd_fat32_controller/ip/sd_fat32_controller_mig_7series_0_1/sd_fat32_controller_mig_7series_0_1/user_design/rtl/sd_fat32_controller_mig_7series_0_1.v" \
    "$ref_dir/../../../bd/sd_fat32_controller/ip/sd_fat32_controller_clk_wiz_0_0/sd_fat32_controller_clk_wiz_0_0_clk_wiz.v" \
    "$ref_dir/../../../bd/sd_fat32_controller/ip/sd_fat32_controller_clk_wiz_0_0/sd_fat32_controller_clk_wiz_0_0.v" \

  ncvhdl -work axi_lite_ipif_v3_0_3 $opts_vhd \
    "$ref_dir/../../../ipstatic/axi_lite_ipif_v3_0/hdl/src/vhdl/ipif_pkg.vhd" \
    "$ref_dir/../../../ipstatic/axi_lite_ipif_v3_0/hdl/src/vhdl/pselect_f.vhd" \
    "$ref_dir/../../../ipstatic/axi_lite_ipif_v3_0/hdl/src/vhdl/address_decoder.vhd" \
    "$ref_dir/../../../ipstatic/axi_lite_ipif_v3_0/hdl/src/vhdl/slave_attachment.vhd" \
    "$ref_dir/../../../ipstatic/axi_lite_ipif_v3_0/hdl/src/vhdl/axi_lite_ipif.vhd" \

  ncvhdl -work lib_pkg_v1_0_2 $opts_vhd \
    "$ref_dir/../../../ipstatic/lib_pkg_v1_0/hdl/src/vhdl/lib_pkg.vhd" \

  ncvhdl -work lib_srl_fifo_v1_0_2 $opts_vhd \
    "$ref_dir/../../../ipstatic/lib_srl_fifo_v1_0/hdl/src/vhdl/cntr_incr_decr_addn_f.vhd" \
    "$ref_dir/../../../ipstatic/lib_srl_fifo_v1_0/hdl/src/vhdl/dynshreg_f.vhd" \
    "$ref_dir/../../../ipstatic/lib_srl_fifo_v1_0/hdl/src/vhdl/srl_fifo_rbu_f.vhd" \
    "$ref_dir/../../../ipstatic/lib_srl_fifo_v1_0/hdl/src/vhdl/srl_fifo_f.vhd" \

  ncvhdl -work lib_cdc_v1_0_2 $opts_vhd \
    "$ref_dir/../../../ipstatic/lib_cdc_v1_0/hdl/src/vhdl/cdc_sync.vhd" \

  ncvhdl -work axi_uartlite_v2_0_10 $opts_vhd \
    "$ref_dir/../../../ipstatic/axi_uartlite_v2_0/hdl/src/vhdl/dynshreg_i_f.vhd" \
    "$ref_dir/../../../ipstatic/axi_uartlite_v2_0/hdl/src/vhdl/uartlite_tx.vhd" \
    "$ref_dir/../../../ipstatic/axi_uartlite_v2_0/hdl/src/vhdl/uartlite_rx.vhd" \
    "$ref_dir/../../../ipstatic/axi_uartlite_v2_0/hdl/src/vhdl/baudrate.vhd" \
    "$ref_dir/../../../ipstatic/axi_uartlite_v2_0/hdl/src/vhdl/uartlite_core.vhd" \
    "$ref_dir/../../../ipstatic/axi_uartlite_v2_0/hdl/src/vhdl/axi_uartlite.vhd" \

  ncvhdl -work xil_defaultlib $opts_vhd \
    "$ref_dir/../../../bd/sd_fat32_controller/ip/sd_fat32_controller_axi_uartlite_0_0/sim/sd_fat32_controller_axi_uartlite_0_0.vhd" \

  ncvhdl -work microblaze_v9_5_3 $opts_vhd \
    "$ref_dir/../../../ipstatic/microblaze_v9_5/hdl/microblaze_v9_5_vh_rfs.vhd" \

  ncvhdl -work xil_defaultlib $opts_vhd \
    "$ref_dir/../../../bd/sd_fat32_controller/ip/sd_fat32_controller_microblaze_0_0/sim/sd_fat32_controller_microblaze_0_0.vhd" \

  ncvhdl -work lmb_v10_v3_0_7 $opts_vhd \
    "$ref_dir/../../../ipstatic/lmb_v10_v3_0/hdl/vhdl/lmb_v10.vhd" \

  ncvhdl -work xil_defaultlib $opts_vhd \
    "$ref_dir/../../../bd/sd_fat32_controller/ip/sd_fat32_controller_dlmb_v10_0/sim/sd_fat32_controller_dlmb_v10_0.vhd" \
    "$ref_dir/../../../bd/sd_fat32_controller/ip/sd_fat32_controller_ilmb_v10_0/sim/sd_fat32_controller_ilmb_v10_0.vhd" \

  ncvhdl -work lmb_bram_if_cntlr_v4_0_7 $opts_vhd \
    "$ref_dir/../../../ipstatic/lmb_bram_if_cntlr_v4_0/hdl/vhdl/lmb_bram_if_funcs.vhd" \
    "$ref_dir/../../../ipstatic/lmb_bram_if_cntlr_v4_0/hdl/vhdl/lmb_bram_if_primitives.vhd" \
    "$ref_dir/../../../ipstatic/lmb_bram_if_cntlr_v4_0/hdl/vhdl/xor18.vhd" \
    "$ref_dir/../../../ipstatic/lmb_bram_if_cntlr_v4_0/hdl/vhdl/parity.vhd" \
    "$ref_dir/../../../ipstatic/lmb_bram_if_cntlr_v4_0/hdl/vhdl/parityenable.vhd" \
    "$ref_dir/../../../ipstatic/lmb_bram_if_cntlr_v4_0/hdl/vhdl/checkbit_handler.vhd" \
    "$ref_dir/../../../ipstatic/lmb_bram_if_cntlr_v4_0/hdl/vhdl/correct_one_bit.vhd" \
    "$ref_dir/../../../ipstatic/lmb_bram_if_cntlr_v4_0/hdl/vhdl/pselect.vhd" \
    "$ref_dir/../../../ipstatic/lmb_bram_if_cntlr_v4_0/hdl/vhdl/pselect_mask.vhd" \
    "$ref_dir/../../../ipstatic/lmb_bram_if_cntlr_v4_0/hdl/vhdl/axi_interface.vhd" \
    "$ref_dir/../../../ipstatic/lmb_bram_if_cntlr_v4_0/hdl/vhdl/lmb_mux.vhd" \
    "$ref_dir/../../../ipstatic/lmb_bram_if_cntlr_v4_0/hdl/vhdl/lmb_bram_if_cntlr.vhd" \

  ncvhdl -work xil_defaultlib $opts_vhd \
    "$ref_dir/../../../bd/sd_fat32_controller/ip/sd_fat32_controller_dlmb_bram_if_cntlr_0/sim/sd_fat32_controller_dlmb_bram_if_cntlr_0.vhd" \
    "$ref_dir/../../../bd/sd_fat32_controller/ip/sd_fat32_controller_ilmb_bram_if_cntlr_0/sim/sd_fat32_controller_ilmb_bram_if_cntlr_0.vhd" \

  ncvhdl -work blk_mem_gen_v8_3_1 $opts_vhd \
    "$ref_dir/../../../ipstatic/blk_mem_gen_v8_3/simulation/blk_mem_gen_v8_3.vhd" \

  ncvhdl -work xil_defaultlib $opts_vhd \
    "$ref_dir/../../../bd/sd_fat32_controller/ip/sd_fat32_controller_lmb_bram_0/sim/sd_fat32_controller_lmb_bram_0.vhd" \

  ncvhdl -work axi_intc_v4_1_5 $opts_vhd \
    "$ref_dir/../../../ipstatic/axi_intc_v4_1/hdl/src/vhdl/double_synchronizer.vhd" \
    "$ref_dir/../../../ipstatic/axi_intc_v4_1/hdl/src/vhdl/shared_ram_ivar.vhd" \
    "$ref_dir/../../../ipstatic/axi_intc_v4_1/hdl/src/vhdl/pulse_synchronizer.vhd" \
    "$ref_dir/../../../ipstatic/axi_intc_v4_1/hdl/src/vhdl/intc_core.vhd" \
    "$ref_dir/../../../ipstatic/axi_intc_v4_1/hdl/src/vhdl/axi_intc.vhd" \

  ncvhdl -work xil_defaultlib $opts_vhd \
    "$ref_dir/../../../bd/sd_fat32_controller/ip/sd_fat32_controller_microblaze_0_axi_intc_0/sim/sd_fat32_controller_microblaze_0_axi_intc_0.vhd" \

  ncvlog -work xil_defaultlib $opts_ver +incdir+"$ref_dir/../../../ipstatic/axi_infrastructure_v1_1/hdl/verilog" \
    "$ref_dir/../../../bd/sd_fat32_controller/ipshared/xilinx.com/xlconcat_v2_1/xlconcat.v" \
    "$ref_dir/../../../bd/sd_fat32_controller/ip/sd_fat32_controller_microblaze_0_xlconcat_0/sim/sd_fat32_controller_microblaze_0_xlconcat_0.v" \

  ncvhdl -work mdm_v3_2_4 $opts_vhd \
    "$ref_dir/../../../ipstatic/mdm_v3_2/hdl/vhdl/mdm_primitives.vhd" \
    "$ref_dir/../../../ipstatic/mdm_v3_2/hdl/vhdl/arbiter.vhd" \
    "$ref_dir/../../../ipstatic/mdm_v3_2/hdl/vhdl/srl_fifo.vhd" \
    "$ref_dir/../../../ipstatic/mdm_v3_2/hdl/vhdl/bus_master.vhd" \
    "$ref_dir/../../../ipstatic/mdm_v3_2/hdl/vhdl/jtag_control.vhd" \
    "$ref_dir/../../../ipstatic/mdm_v3_2/hdl/vhdl/mdm_core.vhd" \
    "$ref_dir/../../../ipstatic/mdm_v3_2/hdl/vhdl/mdm.vhd" \

  ncvhdl -work xil_defaultlib $opts_vhd \
    "$ref_dir/../../../bd/sd_fat32_controller/ip/sd_fat32_controller_mdm_1_0/sim/sd_fat32_controller_mdm_1_0.vhd" \

  ncvhdl -work proc_sys_reset_v5_0_8 $opts_vhd \
    "$ref_dir/../../../ipstatic/proc_sys_reset_v5_0/hdl/src/vhdl/upcnt_n.vhd" \
    "$ref_dir/../../../ipstatic/proc_sys_reset_v5_0/hdl/src/vhdl/sequence_psr.vhd" \
    "$ref_dir/../../../ipstatic/proc_sys_reset_v5_0/hdl/src/vhdl/lpf.vhd" \
    "$ref_dir/../../../ipstatic/proc_sys_reset_v5_0/hdl/src/vhdl/proc_sys_reset.vhd" \

  ncvhdl -work xil_defaultlib $opts_vhd \
    "$ref_dir/../../../bd/sd_fat32_controller/ip/sd_fat32_controller_rst_clk_wiz_0_100M_0/sim/sd_fat32_controller_rst_clk_wiz_0_100M_0.vhd" \

  ncvlog -work xil_defaultlib $opts_ver +incdir+"$ref_dir/../../../ipstatic/axi_infrastructure_v1_1/hdl/verilog" \
    "$ref_dir/../../../../sd_fat32_2.0.srcs/sources_1/bd/sd_fat32_controller/ip/sd_fat32_controller_PmodWIFI_0_0/ipshared/digilentinc.com/pmod_bridge_v1_0/src/pmod_concat.v" \
    "$ref_dir/../../../bd/sd_fat32_controller/ip/sd_fat32_controller_PmodWIFI_0_0/src/PmodWIFI_pmod_bridge_0_0/sim/PmodWIFI_pmod_bridge_0_0.v" \

  ncvhdl -work dist_mem_gen_v8_0_9 $opts_vhd \
    "$ref_dir/../../../ipstatic/dist_mem_gen_v8_0/simulation/dist_mem_gen_v8_0.vhd" \

  ncvhdl -work fifo_generator_v13_0_1 $opts_vhd \
    "$ref_dir/../../../ipstatic/fifo_generator_v13_0/simulation/fifo_generator_vhdl_beh.vhd" \
    "$ref_dir/../../../ipstatic/fifo_generator_v13_0/hdl/fifo_generator_v13_0_rfs.vhd" \

  ncvhdl -work lib_fifo_v1_0_4 $opts_vhd \
    "$ref_dir/../../../ipstatic/lib_fifo_v1_0/hdl/src/vhdl/async_fifo_fg.vhd" \
    "$ref_dir/../../../ipstatic/lib_fifo_v1_0/hdl/src/vhdl/sync_fifo_fg.vhd" \

  ncvhdl -work interrupt_control_v3_1_3 $opts_vhd \
    "$ref_dir/../../../ipstatic/interrupt_control_v3_1/hdl/src/vhdl/interrupt_control.vhd" \

  ncvhdl -work axi_quad_spi_v3_2_6 $opts_vhd \
    "$ref_dir/../../../ipstatic/axi_quad_spi_v3_2/hdl/src/vhdl/comp_defs.vhd" \
    "$ref_dir/../../../ipstatic/axi_quad_spi_v3_2/hdl/src/vhdl/pselect_f.vhd" \
    "$ref_dir/../../../ipstatic/axi_quad_spi_v3_2/hdl/src/vhdl/counter_f.vhd" \
    "$ref_dir/../../../ipstatic/axi_quad_spi_v3_2/hdl/src/vhdl/soft_reset.vhd" \
    "$ref_dir/../../../ipstatic/axi_quad_spi_v3_2/hdl/src/vhdl/xip_cross_clk_sync.vhd" \
    "$ref_dir/../../../ipstatic/axi_quad_spi_v3_2/hdl/src/vhdl/reset_sync_module.vhd" \
    "$ref_dir/../../../ipstatic/axi_quad_spi_v3_2/hdl/src/vhdl/qspi_status_slave_sel_reg.vhd" \
    "$ref_dir/../../../ipstatic/axi_quad_spi_v3_2/hdl/src/vhdl/qspi_startup_block.vhd" \
    "$ref_dir/../../../ipstatic/axi_quad_spi_v3_2/hdl/src/vhdl/qspi_receive_transmit_reg.vhd" \
    "$ref_dir/../../../ipstatic/axi_quad_spi_v3_2/hdl/src/vhdl/qspi_occupancy_reg.vhd" \
    "$ref_dir/../../../ipstatic/axi_quad_spi_v3_2/hdl/src/vhdl/qspi_mode_control_logic.vhd" \
    "$ref_dir/../../../ipstatic/axi_quad_spi_v3_2/hdl/src/vhdl/qspi_mode_0_module.vhd" \
    "$ref_dir/../../../ipstatic/axi_quad_spi_v3_2/hdl/src/vhdl/qspi_look_up_logic.vhd" \
    "$ref_dir/../../../ipstatic/axi_quad_spi_v3_2/hdl/src/vhdl/qspi_fifo_ifmodule.vhd" \
    "$ref_dir/../../../ipstatic/axi_quad_spi_v3_2/hdl/src/vhdl/qspi_cntrl_reg.vhd" \
    "$ref_dir/../../../ipstatic/axi_quad_spi_v3_2/hdl/src/vhdl/qspi_address_decoder.vhd" \
    "$ref_dir/../../../ipstatic/axi_quad_spi_v3_2/hdl/src/vhdl/cross_clk_sync_fifo_1.vhd" \
    "$ref_dir/../../../ipstatic/axi_quad_spi_v3_2/hdl/src/vhdl/cross_clk_sync_fifo_0.vhd" \
    "$ref_dir/../../../ipstatic/axi_quad_spi_v3_2/hdl/src/vhdl/xip_status_reg.vhd" \
    "$ref_dir/../../../ipstatic/axi_quad_spi_v3_2/hdl/src/vhdl/xip_cntrl_reg.vhd" \
    "$ref_dir/../../../ipstatic/axi_quad_spi_v3_2/hdl/src/vhdl/qspi_core_interface.vhd" \
    "$ref_dir/../../../ipstatic/axi_quad_spi_v3_2/hdl/src/vhdl/axi_qspi_xip_if.vhd" \
    "$ref_dir/../../../ipstatic/axi_quad_spi_v3_2/hdl/src/vhdl/axi_qspi_enhanced_mode.vhd" \
    "$ref_dir/../../../ipstatic/axi_quad_spi_v3_2/hdl/src/vhdl/axi_quad_spi.vhd" \
    "$ref_dir/../../../bd/sd_fat32_controller/ip/sd_fat32_controller_PmodWIFI_0_0/src/PmodWIFI_axi_quad_spi_0_0/sim/PmodWIFI_axi_quad_spi_0_0.vhd" \

  ncvhdl -work axi_gpio_v2_0_9 $opts_vhd \
    "$ref_dir/../../../ipstatic/axi_gpio_v2_0/hdl/src/vhdl/gpio_core.vhd" \
    "$ref_dir/../../../ipstatic/axi_gpio_v2_0/hdl/src/vhdl/axi_gpio.vhd" \
    "$ref_dir/../../../bd/sd_fat32_controller/ip/sd_fat32_controller_PmodWIFI_0_0/src/PmodWIFI_axi_gpio_0_0/sim/PmodWIFI_axi_gpio_0_0.vhd" \
    "$ref_dir/../../../bd/sd_fat32_controller/ip/sd_fat32_controller_PmodWIFI_0_0/src/PmodWIFI_axi_gpio_1_0/sim/PmodWIFI_axi_gpio_1_0.vhd" \

  ncvhdl -work axi_timer_v2_0_8 $opts_vhd \
    "$ref_dir/../../../ipstatic/axi_timer_v2_0/hdl/src/vhdl/counter_f.vhd" \
    "$ref_dir/../../../ipstatic/axi_timer_v2_0/hdl/src/vhdl/mux_onehot_f.vhd" \
    "$ref_dir/../../../ipstatic/axi_timer_v2_0/hdl/src/vhdl/tc_types.vhd" \
    "$ref_dir/../../../ipstatic/axi_timer_v2_0/hdl/src/vhdl/timer_control.vhd" \
    "$ref_dir/../../../ipstatic/axi_timer_v2_0/hdl/src/vhdl/count_module.vhd" \
    "$ref_dir/../../../ipstatic/axi_timer_v2_0/hdl/src/vhdl/tc_core.vhd" \
    "$ref_dir/../../../ipstatic/axi_timer_v2_0/hdl/src/vhdl/axi_timer.vhd" \
    "$ref_dir/../../../bd/sd_fat32_controller/ip/sd_fat32_controller_PmodWIFI_0_0/src/PmodWIFI_axi_timer_0_0/sim/PmodWIFI_axi_timer_0_0.vhd" \

  ncvlog -work xil_defaultlib $opts_ver +incdir+"$ref_dir/../../../ipstatic/axi_infrastructure_v1_1/hdl/verilog" \
    "$ref_dir/../../../bd/sd_fat32_controller/ipshared/digilentinc.com/pmodwifi_v1_0/src/PmodWIFI.v" \
    "$ref_dir/../../../bd/sd_fat32_controller/ip/sd_fat32_controller_PmodWIFI_0_0/sim/sd_fat32_controller_PmodWIFI_0_0.v" \

  ncvhdl -work axi_gpio_v2_0_9 $opts_vhd \
    "$ref_dir/../../../bd/sd_fat32_controller/ip/sd_fat32_controller_PmodSD_0_0/src/PmodSD_axi_gpio_0_0/sim/PmodSD_axi_gpio_0_0.vhd" \

  ncvhdl -work axi_quad_spi_v3_2_6 $opts_vhd \
    "$ref_dir/../../../bd/sd_fat32_controller/ip/sd_fat32_controller_PmodSD_0_0/src/PmodSD_axi_quad_spi_0_0/sim/PmodSD_axi_quad_spi_0_0.vhd" \

  ncvlog -work xil_defaultlib $opts_ver +incdir+"$ref_dir/../../../ipstatic/axi_infrastructure_v1_1/hdl/verilog" \
    "$ref_dir/../../../bd/sd_fat32_controller/ip/sd_fat32_controller_PmodSD_0_0/src/PmodSD_pmod_bridge_0_0/sim/PmodSD_pmod_bridge_0_0.v" \
    "$ref_dir/../../../bd/sd_fat32_controller/ipshared/digilentinc.com/pmodsd_v1_0/src/PmodSD.v" \
    "$ref_dir/../../../bd/sd_fat32_controller/ip/sd_fat32_controller_PmodSD_0_0/sim/sd_fat32_controller_PmodSD_0_0.v" \

  ncvhdl -work xil_defaultlib $opts_vhd \
    "$ref_dir/../../../bd/sd_fat32_controller/ip/sd_fat32_controller_axi_gpio_0_0/sim/sd_fat32_controller_axi_gpio_0_0.vhd" \
    "$ref_dir/../../../bd/sd_fat32_controller/ip/sd_fat32_controller_axi_gpio_1_0/sim/sd_fat32_controller_axi_gpio_1_0.vhd" \

  ncvlog -work generic_baseblocks_v2_1_0 $opts_ver +incdir+"$ref_dir/../../../ipstatic/axi_infrastructure_v1_1/hdl/verilog" \
    "$ref_dir/../../../ipstatic/generic_baseblocks_v2_1/hdl/verilog/generic_baseblocks_v2_1_carry_and.v" \
    "$ref_dir/../../../ipstatic/generic_baseblocks_v2_1/hdl/verilog/generic_baseblocks_v2_1_carry_latch_and.v" \
    "$ref_dir/../../../ipstatic/generic_baseblocks_v2_1/hdl/verilog/generic_baseblocks_v2_1_carry_latch_or.v" \
    "$ref_dir/../../../ipstatic/generic_baseblocks_v2_1/hdl/verilog/generic_baseblocks_v2_1_carry_or.v" \
    "$ref_dir/../../../ipstatic/generic_baseblocks_v2_1/hdl/verilog/generic_baseblocks_v2_1_carry.v" \
    "$ref_dir/../../../ipstatic/generic_baseblocks_v2_1/hdl/verilog/generic_baseblocks_v2_1_command_fifo.v" \
    "$ref_dir/../../../ipstatic/generic_baseblocks_v2_1/hdl/verilog/generic_baseblocks_v2_1_comparator_mask_static.v" \
    "$ref_dir/../../../ipstatic/generic_baseblocks_v2_1/hdl/verilog/generic_baseblocks_v2_1_comparator_mask.v" \
    "$ref_dir/../../../ipstatic/generic_baseblocks_v2_1/hdl/verilog/generic_baseblocks_v2_1_comparator_sel_mask_static.v" \
    "$ref_dir/../../../ipstatic/generic_baseblocks_v2_1/hdl/verilog/generic_baseblocks_v2_1_comparator_sel_mask.v" \
    "$ref_dir/../../../ipstatic/generic_baseblocks_v2_1/hdl/verilog/generic_baseblocks_v2_1_comparator_sel_static.v" \
    "$ref_dir/../../../ipstatic/generic_baseblocks_v2_1/hdl/verilog/generic_baseblocks_v2_1_comparator_sel.v" \
    "$ref_dir/../../../ipstatic/generic_baseblocks_v2_1/hdl/verilog/generic_baseblocks_v2_1_comparator_static.v" \
    "$ref_dir/../../../ipstatic/generic_baseblocks_v2_1/hdl/verilog/generic_baseblocks_v2_1_comparator.v" \
    "$ref_dir/../../../ipstatic/generic_baseblocks_v2_1/hdl/verilog/generic_baseblocks_v2_1_mux_enc.v" \
    "$ref_dir/../../../ipstatic/generic_baseblocks_v2_1/hdl/verilog/generic_baseblocks_v2_1_mux.v" \
    "$ref_dir/../../../ipstatic/generic_baseblocks_v2_1/hdl/verilog/generic_baseblocks_v2_1_nto1_mux.v" \

  ncvlog -work axi_infrastructure_v1_1_0 $opts_ver +incdir+"$ref_dir/../../../ipstatic/axi_infrastructure_v1_1/hdl/verilog" \
    "$ref_dir/../../../ipstatic/axi_infrastructure_v1_1/hdl/verilog/axi_infrastructure_v1_1_axi2vector.v" \
    "$ref_dir/../../../ipstatic/axi_infrastructure_v1_1/hdl/verilog/axi_infrastructure_v1_1_axic_srl_fifo.v" \
    "$ref_dir/../../../ipstatic/axi_infrastructure_v1_1/hdl/verilog/axi_infrastructure_v1_1_vector2axi.v" \

  ncvlog -work axi_register_slice_v2_1_7 $opts_ver +incdir+"$ref_dir/../../../ipstatic/axi_infrastructure_v1_1/hdl/verilog" \
    "$ref_dir/../../../ipstatic/axi_register_slice_v2_1/hdl/verilog/axi_register_slice_v2_1_axic_register_slice.v" \
    "$ref_dir/../../../ipstatic/axi_register_slice_v2_1/hdl/verilog/axi_register_slice_v2_1_axi_register_slice.v" \

  ncvlog -work axi_data_fifo_v2_1_6 $opts_ver +incdir+"$ref_dir/../../../ipstatic/axi_infrastructure_v1_1/hdl/verilog" \
    "$ref_dir/../../../ipstatic/axi_data_fifo_v2_1/hdl/verilog/axi_data_fifo_v2_1_axic_fifo.v" \
    "$ref_dir/../../../ipstatic/axi_data_fifo_v2_1/hdl/verilog/axi_data_fifo_v2_1_fifo_gen.v" \
    "$ref_dir/../../../ipstatic/axi_data_fifo_v2_1/hdl/verilog/axi_data_fifo_v2_1_axic_srl_fifo.v" \
    "$ref_dir/../../../ipstatic/axi_data_fifo_v2_1/hdl/verilog/axi_data_fifo_v2_1_axic_reg_srl_fifo.v" \
    "$ref_dir/../../../ipstatic/axi_data_fifo_v2_1/hdl/verilog/axi_data_fifo_v2_1_ndeep_srl.v" \
    "$ref_dir/../../../ipstatic/axi_data_fifo_v2_1/hdl/verilog/axi_data_fifo_v2_1_axi_data_fifo.v" \

  ncvlog -work axi_crossbar_v2_1_8 $opts_ver +incdir+"$ref_dir/../../../ipstatic/axi_infrastructure_v1_1/hdl/verilog" \
    "$ref_dir/../../../ipstatic/axi_crossbar_v2_1/hdl/verilog/axi_crossbar_v2_1_addr_arbiter_sasd.v" \
    "$ref_dir/../../../ipstatic/axi_crossbar_v2_1/hdl/verilog/axi_crossbar_v2_1_addr_arbiter.v" \
    "$ref_dir/../../../ipstatic/axi_crossbar_v2_1/hdl/verilog/axi_crossbar_v2_1_addr_decoder.v" \
    "$ref_dir/../../../ipstatic/axi_crossbar_v2_1/hdl/verilog/axi_crossbar_v2_1_arbiter_resp.v" \
    "$ref_dir/../../../ipstatic/axi_crossbar_v2_1/hdl/verilog/axi_crossbar_v2_1_crossbar_sasd.v" \
    "$ref_dir/../../../ipstatic/axi_crossbar_v2_1/hdl/verilog/axi_crossbar_v2_1_crossbar.v" \
    "$ref_dir/../../../ipstatic/axi_crossbar_v2_1/hdl/verilog/axi_crossbar_v2_1_decerr_slave.v" \
    "$ref_dir/../../../ipstatic/axi_crossbar_v2_1/hdl/verilog/axi_crossbar_v2_1_si_transactor.v" \
    "$ref_dir/../../../ipstatic/axi_crossbar_v2_1/hdl/verilog/axi_crossbar_v2_1_splitter.v" \
    "$ref_dir/../../../ipstatic/axi_crossbar_v2_1/hdl/verilog/axi_crossbar_v2_1_wdata_mux.v" \
    "$ref_dir/../../../ipstatic/axi_crossbar_v2_1/hdl/verilog/axi_crossbar_v2_1_wdata_router.v" \
    "$ref_dir/../../../ipstatic/axi_crossbar_v2_1/hdl/verilog/axi_crossbar_v2_1_axi_crossbar.v" \

  ncvlog -work xil_defaultlib $opts_ver +incdir+"$ref_dir/../../../ipstatic/axi_infrastructure_v1_1/hdl/verilog" \
    "$ref_dir/../../../bd/sd_fat32_controller/ip/sd_fat32_controller_xbar_0/sim/sd_fat32_controller_xbar_0.v" \

  ncvhdl -work xil_defaultlib $opts_vhd \
    "$ref_dir/../../../bd/sd_fat32_controller/ip/sd_fat32_controller_rst_mig_7series_0_75M_0/sim/sd_fat32_controller_rst_mig_7series_0_75M_0.vhd" \

  ncvlog -work xil_defaultlib $opts_ver +incdir+"$ref_dir/../../../ipstatic/axi_infrastructure_v1_1/hdl/verilog" \
    "$ref_dir/../../../bd/sd_fat32_controller/ip/sd_fat32_controller_xbar_1/sim/sd_fat32_controller_xbar_1.v" \

  ncvlog -work axi_clock_converter_v2_1_6 $opts_ver +incdir+"$ref_dir/../../../ipstatic/axi_infrastructure_v1_1/hdl/verilog" \
    "$ref_dir/../../../ipstatic/axi_clock_converter_v2_1/hdl/verilog/axi_clock_converter_v2_1_axic_sync_clock_converter.v" \
    "$ref_dir/../../../ipstatic/axi_clock_converter_v2_1/hdl/verilog/axi_clock_converter_v2_1_axic_sample_cycle_ratio.v" \
    "$ref_dir/../../../ipstatic/axi_clock_converter_v2_1/hdl/verilog/axi_clock_converter_v2_1_axi_clock_converter.v" \

  ncvlog -work xil_defaultlib $opts_ver +incdir+"$ref_dir/../../../ipstatic/axi_infrastructure_v1_1/hdl/verilog" \
    "$ref_dir/../../../bd/sd_fat32_controller/ip/sd_fat32_controller_auto_cc_0/sim/sd_fat32_controller_auto_cc_0.v" \

  ncvlog -work axi_protocol_converter_v2_1_7 $opts_ver +incdir+"$ref_dir/../../../ipstatic/axi_infrastructure_v1_1/hdl/verilog" \
    "$ref_dir/../../../ipstatic/axi_protocol_converter_v2_1/hdl/verilog/axi_protocol_converter_v2_1_a_axi3_conv.v" \
    "$ref_dir/../../../ipstatic/axi_protocol_converter_v2_1/hdl/verilog/axi_protocol_converter_v2_1_axi3_conv.v" \
    "$ref_dir/../../../ipstatic/axi_protocol_converter_v2_1/hdl/verilog/axi_protocol_converter_v2_1_axilite_conv.v" \
    "$ref_dir/../../../ipstatic/axi_protocol_converter_v2_1/hdl/verilog/axi_protocol_converter_v2_1_r_axi3_conv.v" \
    "$ref_dir/../../../ipstatic/axi_protocol_converter_v2_1/hdl/verilog/axi_protocol_converter_v2_1_w_axi3_conv.v" \
    "$ref_dir/../../../ipstatic/axi_protocol_converter_v2_1/hdl/verilog/axi_protocol_converter_v2_1_b_downsizer.v" \
    "$ref_dir/../../../ipstatic/axi_protocol_converter_v2_1/hdl/verilog/axi_protocol_converter_v2_1_decerr_slave.v" \
    "$ref_dir/../../../ipstatic/axi_protocol_converter_v2_1/hdl/verilog/axi_protocol_converter_v2_1_b2s_simple_fifo.v" \
    "$ref_dir/../../../ipstatic/axi_protocol_converter_v2_1/hdl/verilog/axi_protocol_converter_v2_1_b2s_wrap_cmd.v" \
    "$ref_dir/../../../ipstatic/axi_protocol_converter_v2_1/hdl/verilog/axi_protocol_converter_v2_1_b2s_incr_cmd.v" \
    "$ref_dir/../../../ipstatic/axi_protocol_converter_v2_1/hdl/verilog/axi_protocol_converter_v2_1_b2s_wr_cmd_fsm.v" \
    "$ref_dir/../../../ipstatic/axi_protocol_converter_v2_1/hdl/verilog/axi_protocol_converter_v2_1_b2s_rd_cmd_fsm.v" \
    "$ref_dir/../../../ipstatic/axi_protocol_converter_v2_1/hdl/verilog/axi_protocol_converter_v2_1_b2s_cmd_translator.v" \
    "$ref_dir/../../../ipstatic/axi_protocol_converter_v2_1/hdl/verilog/axi_protocol_converter_v2_1_b2s_b_channel.v" \
    "$ref_dir/../../../ipstatic/axi_protocol_converter_v2_1/hdl/verilog/axi_protocol_converter_v2_1_b2s_r_channel.v" \
    "$ref_dir/../../../ipstatic/axi_protocol_converter_v2_1/hdl/verilog/axi_protocol_converter_v2_1_b2s_aw_channel.v" \
    "$ref_dir/../../../ipstatic/axi_protocol_converter_v2_1/hdl/verilog/axi_protocol_converter_v2_1_b2s_ar_channel.v" \
    "$ref_dir/../../../ipstatic/axi_protocol_converter_v2_1/hdl/verilog/axi_protocol_converter_v2_1_b2s.v" \
    "$ref_dir/../../../ipstatic/axi_protocol_converter_v2_1/hdl/verilog/axi_protocol_converter_v2_1_axi_protocol_converter.v" \

  ncvlog -work axi_dwidth_converter_v2_1_7 $opts_ver +incdir+"$ref_dir/../../../ipstatic/axi_infrastructure_v1_1/hdl/verilog" \
    "$ref_dir/../../../ipstatic/axi_dwidth_converter_v2_1/hdl/verilog/axi_dwidth_converter_v2_1_a_downsizer.v" \
    "$ref_dir/../../../ipstatic/axi_dwidth_converter_v2_1/hdl/verilog/axi_dwidth_converter_v2_1_b_downsizer.v" \
    "$ref_dir/../../../ipstatic/axi_dwidth_converter_v2_1/hdl/verilog/axi_dwidth_converter_v2_1_r_downsizer.v" \
    "$ref_dir/../../../ipstatic/axi_dwidth_converter_v2_1/hdl/verilog/axi_dwidth_converter_v2_1_w_downsizer.v" \
    "$ref_dir/../../../ipstatic/axi_dwidth_converter_v2_1/hdl/verilog/axi_dwidth_converter_v2_1_axi_downsizer.v" \
    "$ref_dir/../../../ipstatic/axi_dwidth_converter_v2_1/hdl/verilog/axi_dwidth_converter_v2_1_axi4lite_downsizer.v" \
    "$ref_dir/../../../ipstatic/axi_dwidth_converter_v2_1/hdl/verilog/axi_dwidth_converter_v2_1_axi4lite_upsizer.v" \
    "$ref_dir/../../../ipstatic/axi_dwidth_converter_v2_1/hdl/verilog/axi_dwidth_converter_v2_1_a_upsizer.v" \
    "$ref_dir/../../../ipstatic/axi_dwidth_converter_v2_1/hdl/verilog/axi_dwidth_converter_v2_1_r_upsizer.v" \
    "$ref_dir/../../../ipstatic/axi_dwidth_converter_v2_1/hdl/verilog/axi_dwidth_converter_v2_1_w_upsizer.v" \
    "$ref_dir/../../../ipstatic/axi_dwidth_converter_v2_1/hdl/verilog/axi_dwidth_converter_v2_1_w_upsizer_pktfifo.v" \
    "$ref_dir/../../../ipstatic/axi_dwidth_converter_v2_1/hdl/verilog/axi_dwidth_converter_v2_1_r_upsizer_pktfifo.v" \
    "$ref_dir/../../../ipstatic/axi_dwidth_converter_v2_1/hdl/verilog/axi_dwidth_converter_v2_1_axi_upsizer.v" \
    "$ref_dir/../../../ipstatic/axi_dwidth_converter_v2_1/hdl/verilog/axi_dwidth_converter_v2_1_top.v" \

  ncvlog -work xil_defaultlib $opts_ver +incdir+"$ref_dir/../../../ipstatic/axi_infrastructure_v1_1/hdl/verilog" \
    "$ref_dir/../../../bd/sd_fat32_controller/ip/sd_fat32_controller_auto_us_0/sim/sd_fat32_controller_auto_us_0.v" \
    "$ref_dir/../../../bd/sd_fat32_controller/ip/sd_fat32_controller_auto_us_1/sim/sd_fat32_controller_auto_us_1.v" \


  ncvlog $opts_ver -work xil_defaultlib \
    "glbl.v"

}

# RUN_STEP: <elaborate>
elaborate()
{
  opts="-64bit -relax -access +rwc -messages -logfile elaborate.log -timescale 1ps/1ps"
  libs="-libname unisims_ver -libname unimacro_ver -libname secureip -libname xil_defaultlib -libname axi_lite_ipif_v3_0_3 -libname lib_pkg_v1_0_2 -libname lib_srl_fifo_v1_0_2 -libname lib_cdc_v1_0_2 -libname axi_uartlite_v2_0_10 -libname microblaze_v9_5_3 -libname lmb_v10_v3_0_7 -libname lmb_bram_if_cntlr_v4_0_7 -libname blk_mem_gen_v8_3_1 -libname axi_intc_v4_1_5 -libname mdm_v3_2_4 -libname proc_sys_reset_v5_0_8 -libname dist_mem_gen_v8_0_9 -libname fifo_generator_v13_0_1 -libname lib_fifo_v1_0_4 -libname interrupt_control_v3_1_3 -libname axi_quad_spi_v3_2_6 -libname axi_gpio_v2_0_9 -libname axi_timer_v2_0_8 -libname generic_baseblocks_v2_1_0 -libname axi_infrastructure_v1_1_0 -libname axi_register_slice_v2_1_7 -libname axi_data_fifo_v2_1_6 -libname axi_crossbar_v2_1_8 -libname axi_clock_converter_v2_1_6 -libname axi_protocol_converter_v2_1_7 -libname axi_dwidth_converter_v2_1_7"
  ncelab $opts xil_defaultlib.sd_fat32_controller xil_defaultlib.glbl $libs
}

# RUN_STEP: <simulate>
simulate()
{
  opts="-64bit -logfile simulate.log"
  ncsim $opts xil_defaultlib.sd_fat32_controller -input simulate.do
}
# Script usage
usage()
{
  msg="Usage: sd_fat32_controller.sh [-help]\n\
Usage: sd_fat32_controller.sh [-lib_map_path]\n\
Usage: sd_fat32_controller.sh [-reset_run]\n\
Usage: sd_fat32_controller.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}


# Launch script
run $1 $2
