# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/FPGA/Nexys4_Master.xdc

# Block Designs: C:/Users/User/Documents/Vivado Projects/Main/teplo_1/teplo_1.srcs/sources_1/bd/design_3/design_3.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_3 || ORIG_REF_NAME==design_3}]

# IP: C:/Users/User/Documents/Vivado Projects/Main/teplo_1/teplo_1.srcs/sources_1/bd/design_3/ip/design_3_floating_point_0_0/design_3_floating_point_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_3_floating_point_0_0 || ORIG_REF_NAME==design_3_floating_point_0_0}]

# Block Designs: C:/Users/User/Documents/Vivado Projects/Main/teplo_1/teplo_1.srcs/sources_1/bd/design_2/design_2.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2 || ORIG_REF_NAME==design_2}]

# IP: C:/Users/User/Documents/Vivado Projects/Main/teplo_1/teplo_1.srcs/sources_1/bd/design_2/ip/design_2_floating_point_0_0/design_2_floating_point_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_floating_point_0_0 || ORIG_REF_NAME==design_2_floating_point_0_0}]

# Block Designs: C:/Users/User/Documents/Vivado Projects/Main/teplo_1/teplo_1.srcs/sources_1/bd/design_1/design_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1}]

# IP: C:/Users/User/Documents/Vivado Projects/Main/teplo_1/teplo_1.srcs/sources_1/bd/design_1/ip/design_1_floating_point_0_0/design_1_floating_point_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_floating_point_0_0 || ORIG_REF_NAME==design_1_floating_point_0_0}]

# XDC: c:/Users/User/Documents/Vivado Projects/Main/teplo_1/teplo_1.srcs/sources_1/bd/design_3/ip/design_3_floating_point_0_0/design_3_floating_point_0_0_ooc.xdc

# XDC: C:/Users/User/Documents/Vivado Projects/Main/teplo_1/teplo_1.srcs/sources_1/bd/design_3/design_3_ooc.xdc

# XDC: c:/Users/User/Documents/Vivado Projects/Main/teplo_1/teplo_1.srcs/sources_1/bd/design_2/ip/design_2_floating_point_0_0/design_2_floating_point_0_0_ooc.xdc

# XDC: C:/Users/User/Documents/Vivado Projects/Main/teplo_1/teplo_1.srcs/sources_1/bd/design_2/design_2_ooc.xdc

# XDC: c:/Users/User/Documents/Vivado Projects/Main/teplo_1/teplo_1.srcs/sources_1/bd/design_1/ip/design_1_floating_point_0_0/design_1_floating_point_0_0_ooc.xdc

# XDC: C:/Users/User/Documents/Vivado Projects/Main/teplo_1/teplo_1.srcs/sources_1/bd/design_1/design_1_ooc.xdc
