# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/FPGA/Trash/calc_2/calc_1.srcs/sources_1/bd/calc_check/ip/calc_check_floating_point_0_0/calc_check_floating_point_0_0.xci
# IP: The module: 'calc_check_floating_point_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/FPGA/Trash/calc_2/calc_1.srcs/sources_1/bd/calc_check/ip/calc_check_floating_point_0_0/calc_check_floating_point_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'calc_check_floating_point_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: D:/FPGA/Trash/calc_2/calc_1.srcs/sources_1/bd/calc_check/ip/calc_check_floating_point_0_0/calc_check_floating_point_0_0.xci
# IP: The module: 'calc_check_floating_point_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/FPGA/Trash/calc_2/calc_1.srcs/sources_1/bd/calc_check/ip/calc_check_floating_point_0_0/calc_check_floating_point_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'calc_check_floating_point_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
