# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/Calculations/project_2/project_1.cache/wt [current_project]
set_property parent.project_path D:/Calculations/project_2/project_1.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
add_files D:/Calculations/project_2/project_1.srcs/sources_1/bd/calc/calc.bd
set_property used_in_implementation false [get_files -all d:/Calculations/project_2/project_1.srcs/sources_1/bd/calc/ip/calc_floating_point_0_0/calc_floating_point_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Calculations/project_2/project_1.srcs/sources_1/bd/calc/ip/calc_floating_point_1_0/calc_floating_point_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Calculations/project_2/project_1.srcs/sources_1/bd/calc/ip/calc_floating_point_2_0/calc_floating_point_2_0_ooc.xdc]
set_property used_in_implementation false [get_files -all D:/Calculations/project_2/project_1.srcs/sources_1/bd/calc/calc_ooc.xdc]
set_property is_locked true [get_files D:/Calculations/project_2/project_1.srcs/sources_1/bd/calc/calc.bd]

read_verilog -library xil_defaultlib {
  D:/Calculations/project_2/project_1.srcs/sources_1/bd/calc/hdl/calc_wrapper.v
  D:/Calculations/project_2/project_1.srcs/sources_1/new/main.v
}
read_xdc D:/Calculations/project_2/project_1.srcs/constrs_1/imports/FPGA/Nexys4_Master.xdc
set_property used_in_implementation false [get_files D:/Calculations/project_2/project_1.srcs/constrs_1/imports/FPGA/Nexys4_Master.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
synth_design -top main -part xc7a100tcsg324-1
write_checkpoint -noxdef main.dcp
catch { report_utilization -file main_utilization_synth.rpt -pb main_utilization_synth.pb }
